### ISSUE TITLE
Cucumber js should not output ANSI colours when no TTY is present or output is being piped

### ISSUE THREAD

**Issue by AndrewVos** [cucumber/cucumber-js#1050]
On version `4.0.0` piping cucumber output to another app should not write out colours.

Here's what it looks like when you do `./node_modules/cucumber/bin/cucumber-js | less`:

![image](https://user-images.githubusercontent.com/363618/37288386-0d3e4010-25ff-11e8-9bd6-c3f9345aaba2.png)

`colors.js` does attempt to do this, but doesn't quite manage it for some reason: https://github.com/Marak/colors.js/blob/cc857f297748633785b2bcf555f226930c8dee4d/lib/system/supports-colors.js#L69

This PR was closed in favour of another PR, but the other PR didn't solve the TTY issue: https://github.com/cucumber/cucumber-js/pull/315

**Comment by charlierudolph** [comment]
Cucumber by default enables colors and only disables if specified by the option: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#colors. Thus the supports-colors part is not used.

Since cucumber outputs to multiple streams (stdout + files) this gets a bit tricky. For each stream, we can check if isTTY but then I'm uncertain how to merge that data with the options. You can output colors to file and then if you `cat` the file it will be colored. How does the following sound @AndrewVos?

- if the user specified for colors to be enabled / disabled that takes precedent.
- otherwise: check per stream if its tty, if false colors are disabled, otherwise enabled

**Comment by AndrewVos** [comment]
Hiya, yeah that sounds quite logical to me. 

That's what rspec does too if I recall correctly.

Thanks for replying to my issue.

**Comment by charlierudolph** [comment]
Fixed in 0415ddef3af75781882c1e725d6b7d43c794e962
