### ISSUE TITLE
Process hangs until step promise not pending

### ISSUE THREAD

**Issue by kyoheiyazawa** [cucumber/cucumber-js#1067]
If an async step times out because a promise is stuck in pending, I would expect the cucumber-js process to exit after the timeout is triggered.  
  
However, in actuality, the cucumber-js process hangs until the offending promise resolves or rejects, even though the timeout is triggered correctly.  
  
We have had a few Cucumber jobs in our CI pipeline hang indefinitely due to some problematic Selenium webdriver commands in steps that returned a frozen promise. The step timeout did not save us from this situation, although we were under the impression that it would.

I have created a bare-bones repro case here: https://github.com/kyoheiyazawa/cucumber-js-timeout-demo
Verified under the following setup:
Node v8.9.4
Mac OS 10.12.6
  
Would you consider this a bug, or are we misunderstanding how the step timeout should behave?

**Comment by charlierudolph** [comment]
The process hangs due to cucumber waiting for the event loop to exit. This is [configurable](https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#exiting). The default was chosen as there are otherwise many times when something has been unable to finish its shutdown.

I'm don't know of a better solution.

**Comment by kyoheiyazawa** [comment]
I missed this option in the docs, thanks for your help @charlierudolph
