### ISSUE TITLE
Fail when promise-style step missing return

### ISSUE THREAD

**Issue by ncjones** [cucumber/cucumber-js#1073]
When using the promise-style step definition it's very easy to forget to return a promise. This can result in flaky tests or (worse) evergreen tests. I would like Cucumber to fail a step when it does not return a promise.

**Comment by charlierudolph** [comment]
Hmm. Interesting. I don't know how well that would work in practice. You want to have the option to force every step to use a specific interface and error out otherwise? Even if you force a step to return a promise by using an async function, if you forget an await / return you still hit the same bug as you aren't waiting for a promise to resolve.

**Comment by arjun1092** [comment]
@charlierudolph  Facing the same overhead.

**Comment by charlierudolph** [comment]
Closing in favor of #996
