### ISSUE TITLE
add --require-module-options to add module options

### ISSUE THREAD

**Issue by victor-perez** [cucumber/cucumber-js#1083]
Currently it not possible to pass module options along via the CLI. In my case I need this for Babel where I want to pass the `only` (https://babeljs.io/docs/usage/babel-register/#specifying-options) option to the module. This should be possible via the `.babelrc` but a bug that only will be fixed in Babel 7 (https://github.com/babel/babel/issues/4082#issuecomment-289122079) prevent me now from doing it via de `.babelrc`
I see on at (https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L61) that only the module is loaded what could be changed to `supportCodeRequiredModules.map({module, options}=> require(module)(options))`

**Comment by charlierudolph** [comment]
I think you can work around this easily enough by adding a file like `custom_babel_register.js` which requires babel-register passing in the options and pass that as the first require option. 
```
--require custom_babel_register.js --require <step defs / support>
```
I'd prefer that as it allows cucumber to not build in this option. I think we could add a note to the CLI doc since babel is pretty popular

**Comment by charlierudolph** [comment]
Closing with workaround. Please reopen if needed

**Comment by Izhaki** [comment]
#1161
