### ISSUE TITLE
Wrong total time value in case of parallel execution

### ISSUE THREAD

**Issue by znevrly** [cucumber/cucumber-js#1155]
Hi,
when tests are are executed, last row is value with total elapsed time. I have tests duration about 8 minutes, when there are executed parallelly then actual time is below 1 minute but console total time is still about original 8 minutes.

**Comment by charlierudolph** [comment]
Yeah, I'm not sure what to really do there. The current time reported is the time that steps were running. In a serial run of cucumber the actual execution time minus the reported time gives the overhead of cucumber loading the files / running / reporting. In parallel, the reported time can be higher than the actual time as when multiple steps are running in parallel each is adding to the reported time.

**Comment by znevrly** [comment]
Would not require architectural changes so this would be also possible? https://github.com/cucumber/cucumber-js/issues/1153

**Comment by krishna01012002** [comment]
Please help me understanding of best use of BDD and feature files.
I have Rest calls and need to validate json response data , Can I give expected response data from feature file as mentioned below? or should I pass expected data from external files(csv or excel).
if expected response data changes in future , is it good idea to change inside feature files ? or we need to follow TDD process?

I am using as below in .feature and working fine.
Scenario:
Then response includes the following in any order
| data[*].username                                                            | 1111 |
   | data[*].phoneNumbers[*].phoneNumber                  | 122-222-2222        |
| data[*].retailLocationRoles[*].securityRoleId            | 10 |

Otherwise should I keep expected response data in external files and read inside of code? is it best practice ?K
Kindly help me it is an urgent, as I am designing REST with cucumber framework

Some one suggesting me to keep data in external files read inside of code , and saying not good idea to change feature file when response data changes?
Thanks for reading . Kindly help me.

**Comment by charlierudolph** [comment]
@krishna01012002 please use our support forums. @znevrly I'll add a note to the parallel documentation that the time reported by the summary formatter is for the sum of total time running steps (and thus most likely higher than the actual runtime) and you can use other tools to see the total runtime for cucumber
