### ISSUE TITLE
Is there a CucumberJS API to pass in features as raw strings?

### ISSUE THREAD

**Issue by chamberlainpi** [cucumber/cucumber-js#1308]
Hey! I'm new to CucumberJS and was wondering if there's any way to use this as a node module, like importing/requiring the cucumber library and running tests by passing the features as **an array of strings**, instead of pointing to a folder of features files.

Something along the lines like:

```
const cucumber = require('cucumber');
const featuresArr = loadFeaturesStrings('http://some.where.com/');

const results = await cucumber.run({
  features: featuresArr,
  steps: require('./steps.js')
});
```

Can cucumber be used in this way? Or does it absolutely have to have the features written to the file-system first?

**Comment by Izhaki** [comment]
This is possible, and exactly what is done in the [browser example](https://github.com/cucumber/cucumber-js/blob/036a7b1e141b0ace4b7cf66dbfb1bc8fcdfcabfa/example/index.ts), specifically here:

```js
  const gherkinMessageStream = Gherkin.fromSources(
    [
      messages.Envelope.fromObject({
        source: {
          data: featureEditor.getValue(), // < getValue() returns a feature as string
          uri: 'example.feature',
        },
      }),
    ],
    { newId }
  )
```

But as you'll notice, this setup is slightly more complicated as you need to use low-level API

**Comment by chamberlainpi** [comment]
@Izhaki does the `uri` property have to be specified? Can I just specify the feature string in the source object’s `data` property?

**Comment by Izhaki** [comment]
When read from the file system, the `uri` is ultimately the 'path' to the feature file.

When you create one manually (as we do in the example above), you still have to provide some "file path", although we don't have a real file (or a real path). So you can just made up whatever you want.

The whole API, including error reports structures etc. are based on the assumption that each feature comes from a file (which is by far the most common use case). That' what `uri` is.

**Comment by jacobwicks** [comment]
I am trying to figure out how to pass feature files to cucumber as strings. 

I have the same use case as @chamberlainpi , who asked here:

>[Is there] any way to use [cucumber js] as a node module, like importing/requiring the cucumber library and running tests by passing the features as an array of strings, instead of pointing to a folder of features files.

>Something along the lines like:
```
const cucumber = require('cucumber');
const featuresArr = loadFeaturesStrings('http://some.where.com/');

const results = await cucumber.run({
  features: featuresArr,
  steps: require('./steps.js')
});
```

That is exactly what I want to do. I want to give my users a GUI that will let them create features. Then I want to take the features that they have created and pass them to cucumber as a parameter of an async function. I want to await the execution of cucumber, get the results back, then display the results to my users. 

But I have been working on this for days and I cannot figure out what I need to do to make it work. 

@Izhaki responded to chamberlainpi's post. Izhaki says 

>This is possible, and exactly what is done in the [browser example](https://github.com/cucumber/cucumber-js/blob/036a7b1e141b0ace4b7cf66dbfb1bc8fcdfcabfa/example/index.ts), specifically here:
```
  const gherkinMessageStream = Gherkin.fromSources(
    [
      messages.Envelope.fromObject({
        source: {
          data: featureEditor.getValue(), // < getValue() returns a feature as string
          uri: 'example.feature',
        },
      }),
    ],
    { newId }
  )
```

I looked at the code in the example that Izhaki linked and I can't figure out how to reproduce it locally.

I see that index.html uses two scripts, cucumber.js and browser-example.js.
```
  <script type="text/javascript" src="cucumber.js"></script>
  <script type="text/javascript" src="browser-example.js"></script>
```

I'm having real difficulty making a working file based on the browser example index.ts because it seems like the example code is using a different export than I am getting from the cucumber I have installed in node_modules.

The example code generates gherkinMessageStream, then uses Cucumber.parseGherkinMessageStream to parse it into an array of strings assigned to const pickleIds.
```
const pickleIds = Cucumber.parseGherkinMessageStream({
```
But I get 
```
TypeError: Cucumber.parseGherkinMessageStream is not a function
```
Also, there is no parseGherkinMessageStream exported from the node_module cucumber. I searched the folder and couldn't find anything called parseGherkinMessageStream.

I can see the code for parseGherkinMessageStream in [src/cli/helpers.ts](https://github.com/cucumber/cucumber-js/blob/master/src/cli/helpers.ts) on github. But I have not been able to access it using cucumber from my node_modules folder.

If I comment out the use of parseGherkinMessageStream and just assign an empty array to pickleIds, 
```
    const pickleIds: string[] = [];
```
cucumber does run and outputs 

```
0 scenarios
0 steps
0m00.000s
```

So I feel like I am close. But I am completely stumped at this point. I have read the docs and everything I could find on the internet & stackoverflow.

Here's my whole index.ts file. How can I get this working?  

```
import { EventEmitter } from 'events';
import Gherkin from 'gherkin';
import { messages, IdGenerator } from 'cucumber-messages';
const Cucumber = require('cucumber');

const featureString = `Feature: Simple maths
In order to do maths
As a developer
I want to increment variables

Scenario: easy maths
  Given a variable set to 1
  When I increment the variable by 1
  Then the variable should contain 2

Scenario Outline: much more complex stuff
  Given a variable set to <var>
  When I increment the variable by <increment>
  Then the variable should contain <result>

  Examples:
    | var | increment | result |
    | 100 |         5 |    105 |
    |  99 |      1234 |   1333 |
    |  12 |         5 |     18 |`;

const { uuid } = IdGenerator;

async function runFeature(): Promise<boolean> {
    const eventBroadcaster = new EventEmitter();

    const eventDataCollector = new Cucumber.formatterHelpers.EventDataCollector(
        eventBroadcaster
    );

    const newId = uuid();
    const gherkinMessageStream = await Gherkin.fromSources(
        [
            messages.Envelope.fromObject({
                source: {
                    data: featureString,
                    uri: 'example.feature',
                },
            }),
        ],
        { newId }
    );

    const pickleIds = Cucumber.parseGherkinMessageStream({
        cwd: '',
        eventBroadcaster,
        eventDataCollector,
        gherkinMessageStream,
        pickleFilter: new Cucumber.PickleFilter({ cwd: '' }),
        order: 'defined',
    });

    Cucumber.supportCodeLibraryBuilder.reset('', newId);

    const supportCodeLibrary = await Cucumber.supportCodeLibraryBuilder.finalize();

    const formatterOptions = {
        cwd: '/',
        eventBroadcaster,
        eventDataCollector,
        parsedArgvOptions: {
            colorsEnabled: true,
        },
        log(data: string) {
            console.log(data);
        },
        supportCodeLibrary,
    };
    Cucumber.FormatterBuilder.build('progress', formatterOptions);

    const runtime = new Cucumber.Runtime({
        eventBroadcaster,
        eventDataCollector,
        newId,
        options: {},
        pickleIds,
        supportCodeLibrary,
    });

    return runtime.start();
}

runFeature();
```
