### ISSUE TITLE
Unable to make Typescript work on cucumber with react

### ISSUE THREAD

**Issue by ambroiseRabier** [cucumber/cucumber-js#1373]
I have checked:
- https://github.com/hdorgeval/cucumber-ts-starter
- https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#transpilers

I have freshly created CRA (Create React App) project (with typescript feature at install).

Typescript files are ignored when putting `'` between the file path. Like `--require 'features/**/*.ts'`. A throw error on first line is getting ignored.

A NPM script like this one `cucumber-js --require-module ts-node/register --require features/**/*.ts`, throw error:
```
import { Given } from 'cucumber';
       ^

SyntaxError: Unexpected token {

```

I also tried the method with a custom tsconfig mentionned, without success.

Is the typescript support broken?

EDIT: Same issue as here https://github.com/Microsoft/TypeScript/issues/26018#issuecomment-498859848

**Comment by ambroiseRabier** [comment]
Ok wow, complaining on github does help fixing the issue.
So, add a tests.setup.js like said but with `module: "commonjs"`:
```js

require('ts-node').register({
  transpileOnly: true,
  compilerOptions: {
    "module": "commonjs",
  },
});

```

NPM script bellow:
```json
{
"cucumber": "cucumber-js --require features/tests.setup.js --require features/**/*.ts",
}
```
double check that the path used by require is correct. Because if the file isn't found the CLU is not going to tell you.

**Comment by Izhaki** [comment]
> "module": "commonjs",

This is odd. To save me time, can you share the repo? Exact steps to reproduce?

> Because if the file isn't found the CLU is not going to tell you.

This is also odd. I reckon that if indeed such is the case it'll need a fix.

**Comment by ambroiseRabier** [comment]
@Izhaki I have made this repo for you: https://github.com/ambroiseRabier/temp-issue-cucumber

**Comment by Izhaki** [comment]
Which node version are you using?

**Comment by Izhaki** [comment]
Super useful.

# Commonjs

So create-react-app now defaults to `esnext`. This is not going to work with cucumber because Node doesn't support `import` statement (not in the way you would hope, anyway).

So if your files are typescript, cucumber has to be explicitly configured with `commonjs`.

I reckon people are going to experience this issue more and more.

So I'll fix the doc (I'll also promote typescript as its popularity is growing now babel transpile it).

# Requiring a missing file

Confirmed.

I just had:

```
"cucumber": "cucumber-js --require-module ts-node/register --require 'features/not.there.js' --require features/**/*.ts",
```

And it doesn't complain about `features/not.there.js`.

I'm going to have a look at it

# Quotations issues

I didn't quite understand from the repo what the problem is or how to reproduce it.

Once I change in `tsconfig.json` `modules` to `commonjs`, `cucumber`, `cucumberIgnoreFile` and `cucumberIgnoreFileToo` all working fine for me:

```
$ cucumber-js --require-module ts-node/register --require 'features/**/*.ts'
...

1 scenario (1 passed)
3 steps (3 passed)
0m00.001s
✨  Done in 2.48s.
```

Mind you, I'm on a Mac.

Can you elaborate on this a bit more?

**Comment by ambroiseRabier** [comment]
I have renamed `cucumber` script to `cucumberTypescriptNo`.

About the quotation issue, I still have it. I have added two npm scripts:
```
    "cucumberOK": "cucumber-js --require features/tests.setup.js --require features/helpers/steps.ts",
    "cucumberIgnoreFileTS": "cucumber-js --require features/tests.setup.js --require 'features/helpers/steps.ts'"
```
The first lineis how I fixed the issue. Notice I did not change my original tsconfig.json, but made another one (tests.setup.js) with the help of the doc. However, if I follow the same steps as you, and modify my origial tsconfig.json and run `"cucumberIgnoreFile": "cucumber-js --require-module ts-node/register --require 'features/**/*.ts'"`, I still get the same issue (while `"cucumberTypescriptNo": "cucumber-js --require-module ts-node/register --require features/**/*.ts"` will be working with tsconfig.json modified like you). `cucumberIgnoreFileToo` is also being ignored.

I am on Windows 10 with git bash.

**Comment by Izhaki** [comment]
When requiring a file that isn't there, it fails silently because of [this code](https://github.com/cucumber/cucumber-js/blob/1b5fd1e7fc9e5710f6ff1c574e3a4feb63832ae0/src/cli/configuration_builder.ts#L120):

```javascript
        const matches = await promisify(glob)(unexpandedPath, {
          absolute: true,
          cwd: this.cwd,
        })
```

Basically, for a file that doesn't exist matches will be an empty array.

@charlierudolph I believe we should throw in such case. Any objections?
