### ISSUE TITLE
SummaryFormatter is not working properly when we pass absolute path to feature

### ISSUE THREAD

**Issue by ramanicsegnxt** [cucumber/cucumber-js#1395]
We are using protractor and cucumber as our test framework. When we pass the feature file path as an absolute path from protractor config, we are facing issues after the test run is finished, JSON file is not generated.

Instead, we are getting error as 

 **E/launcher - Error: TypeError: Cannot read property 'name' of undefined**

When I try to deep dive into the issue. I have noted that in the **cucumber\lib\formatter\helpers\event_data_collector.js** in the **getTestCaseAttempts** method there is a logic to split URI and line number where **":"** is used as separator. Here, In our case 
testCaseAttemptKey is going like an absolute path (i.e. C:\Test\Feature:9:2). so it is framing URI as C and line as \Test\Feature. So we are not getting the expected output.

Kindly help me to resolve this issue.

Currently we are using 
node :: 12.18.3
cucumber :: 6.0.5
protractor :: 7.0.0
protractor-cucumber-framework :: 6.2.1

Thanks

**Comment by davidjgoss** [comment]
Thanks for reporting @ramanicsegnxt.

This should be fixed in the forthcoming 7.0.0 release, where the events model is significantly reworked and the internal maps of test case attempts etc are no longer keyed on the colon-separated expression you mentioned, but rather using a simple unique id.

In the meantime you should be able to verify this using the [release candidate of `@cucumber/cucumber`](https://www.npmjs.com/package/@cucumber/cucumber) - though bear in mind there a few breaking changes in there as well.

**Comment by davidjgoss** [comment]
7.0.0 is now released, see [the changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for migration instructions. Thanks!
