### ISSUE TITLE
Remove browser example

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-js#1437]
I'm about to make a release, and the release instructions tell me I should verify that the browser example works. I'm struggling to make it work, and I doubt many people are using it. I would like to remove it. It's too much to maintain and I don't see the value in it.

**Comment by davidjgoss** [comment]
To be honest I’ve wondered for a while what the use case is for running cucumber in the browser rather than in Node (aside from the kind of interactive demo the browser example gives)

**Comment by aslakhellesoy** [comment]
I think it was a pipe dream @jbpros had 10 years ago that never came to fruition :-)

**Comment by jbpros** [comment]
Not true! ;) One use case was at the BBC, we embedded a suite run on a USB stick to run on smart TVs. The whole thing was running on the browser and sending results back through XHR! Amazing tech ;)

It was also to align with jasmine in-browser runners and other similar approaches, back in the day... 

Anyway, now that we have cucumber-electron and how things have matured generally, I think we can stop supporting this!

**Comment by deepziem** [comment]
@jbpros Here are my thoughts .. if you need electron based cucumber / web testing [ browser ?] to be faster then they need to have core javascript replacing the selenium API's. was there/is there a library that can give a testing framework?

Else you still need the element based actions that selenium provides and it will back to same speed right ?

**Comment by vytch** [comment]
Hi, I was really interested in that browser example. I am trying to make it work also and it might not be working with the current version of cucumber. 

For example the example code does not match the current typescript definition.

Would it be ok to update the example to reflect the current type definition?

Thanks

Vy

**Comment by davidjgoss** [comment]
@vytch whats your use case for running cucumber in the browser vs in node?

**Comment by vytch** [comment]
@davidjgoss I wanted to write a chrome extension.

**Comment by jbpros** [comment]
@deepziem the DOM API is all you need, really. Now if you want so more declarative/expressive API, there are several tools out there. [browser-monkey](https://browsermonkey.org/#/introduction) is one of them.

**Comment by jbpros** [comment]
@vytch what did you want the chrome extension to do?

**Comment by vytch** [comment]
Hi,
I am writing a chrome extension to help doing accessibility testing using a chrome extension.
The chrome extension runs a test suite, similar to a classic end-to-end test and run axe when the dom changes.
I have done that already and I am happy with the result.

One feature I wanted to add is Gherkin support. Because I wanted to hand that tool over to people with little programming skills. Also because I quite like Gherkin.

What I need from cucumber-js is pretty much what that browser example does:

- parse the Gherkin code (from a text-area)
- matching that against the step definition (in-build in the extension) 
- run the test
- collect the result

I am struggling to re-use the example. I just need some guidance on the minimum I need to do the above.
One thing I which I had is a bit of explanations on how the example is put together:

- Cucumber.formatterHelpers
- Cucumber.parseGherkinMessageStream

Why do I need a stream for a formatter, and why the example does not need one?

Btw I am happy to help with documentation if that's helpful.

**Comment by vytch** [comment]
Hi, 

Thank you for your replies, I ended up working with gherk which is more suitable to my needs.

Thanks

**Comment by davidjgoss** [comment]
@charlierudolph @aslakhellesoy what do we think on this? Pre 7.0.0 would be a good time to do it if we're going to.

**Comment by charlierudolph** [comment]
I'm good removing it. I think the main use case was just to give a demo
