### ISSUE TITLE
Insufficient documentation in CLI.md

### ISSUE THREAD

**Issue by michaelm-rsi** [cucumber/cucumber-js#1460]
In the docs currently:

> Use --require <GLOB|DIR|FILE> to require support files before executing the features. Uses glob patterns. If not used, the following files are required:
> 
> If the features live in a features directory (at any level)
> features/**/*.js
> Otherwise
> <DIR>/**/*.js for each directory containing the selected features
> Automatic loading is disabled when this option is specified, and all loading becomes explicit.

So how the HELL are we supposed to do explicit loading??  That's documented nowhere.

**Comment by aslakhellesoy** [comment]
Please use a more courteous tone and I might be inclined to give you some pointers.

**Comment by michaelm-rsi** [comment]
It took 4 more hours, but I found an example in a stack overflow post on about page 4 of google's results

`cucumber.js test/functional/features/xyz.feature 
--require test/functional/step_definitions/ 
--require features/support/ --format=pretty`

The docs do not point out the --require opt can be called multiple times. This is highly non-standard so it needs to be documented.  The documentation implies that require steps have to be in glob format for the directory to be traversed - this is also false.

When I get done with what I'm doing I'll fork, correct the doc file in question, and issue a pull request.

My tone was off, but no apology will be offered due to the snarky response which was far more out of line then me dropping an explicative directed at no one in particular in response to poor documentation. I wasn't being personal.  You - aslak - were being personal and unprofessional.

Documentation is hard to write, and in some corner cases harder to write than the original code. You should never take it personally when someone gets exasperated trying to follow something you wrote. Cucumber has a worse situation than most codebases through no fault of it's own. Results for Java and Ruby get in the way even if you specificy cucumber.js.  Making the situation even worse is there considerable differences between this newest version and its antecedents, but most of the search results concern that antecedent.  So it's critical that when someone finally does find the correct documentation here that it is accurate and complete.  Currently it is not, but I'll take some time to try to help out with that.

**Comment by mattwynne** [comment]
Hi @michaelm-rsi, welcome to the Cucumber community 😃👋

I'm glad you've found your answer. I can see you were really frustrated because the documentation was incomplete. Thanks for your offer to help improve the docs, that's much appreciated. There are thousands of imperfections all over the Cucumber codebases, and it's thanks to people who take the initiative to scatch their own itches that these things get fixed.

If you need an urgent answer another time, I'd suggest trying the [community Slack channel](https://cucumber.io/support/#slack) where (even on a weekend) you're more likely to get a quick response to help you get un-stuck.

When I re-read your original message, while your frustration comes through loud and clear, I find it quite difficult to actually work out what it is you're actually trying to do, and how to help you. I suggest that [this guide](https://stackoverflow.com/help/how-to-ask) would be a helpful reference to ensure that when you do ask a question on a forum like this, people are able to help you without needing to follow up with more clarifying questions first. This is both a respectful way to treat the people who give their time to answer questions on these forums, and also more likely to get you the answer you need, sooner. 👍

I can see there's some tension arising in this exchange, so I'll just point to the [Cucumber community code of conduct](https://github.com/cucumber/cucumber/blob/master/CODE_OF_CONDUCT.md), which is a good reminder of the kind of community we aspire to be. ❤️
