### ISSUE TITLE
compilation issues with typescript

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js#1532]
When compiling a TypeScript project using v7 with this pretty standard `tsconfig.json`:

```jsom
{
  "include": [
    "support/**/*.ts"
  ],
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitReturns": true
  }
}
```

We see these two compilation errors:

```
node_modules/@cucumber/cucumber/lib/runtime/attachment_manager/index.d.ts:2:8 - error TS1259: Module '"stream"' can only be default-imported using the 'esModuleInterop' flag

2 import stream from 'stream';
         ~~~~~~

  node_modules/@types/node/stream.d.ts:331:5
    331     export = internal;
            ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/@cucumber/messages/dist/src/index.d.ts:9:25 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

9 import { version } from '../package.json';
                          ~~~~~~~~~~~~~~~~~
```

This can be easily worked around by adding `esModuleInterop` and `resolveJsonModule` compiler options, but it'd be better if we didn't have to.

- [x] Remove need for `esModuleInterop`
- [ ] Remove need for `resolveJsonModule`
- [ ] Remove need for `@types/lodash`

**Comment by jan-molak** [comment]
@davidjgoss I agree, this is problematic because any project that depends on `@cucumber/cucumber` will now have to enable those two flags. I'd prefer to avoid having to do it, if possible.

`esModuleInterop` could be avoided by using:
```typescript
import * as stream from 'stream'
```
instead of:
```typescript
import stream from 'stream'
```

And since the only reason to use `resolveJsonModule` seems to be to read the version of the `@cucumber/cucumber` module, perhaps `require` or even `fs.readFileSync` could be used instead?

**Comment by jan-molak** [comment]
@davidjgoss - I've just noticed the same issue with `resolveJsonModule` present in `@cucumber/cucumber-messages`:

```
node_modules/@cucumber/messages/dist/src/index.d.ts:9:25 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```

**Comment by code4muktesh** [comment]
If you are consuming the cucumber V7 in typescript project then can temporary fix it adding `compilerOptions` in tsconfig.json file as
`"skipLibCheck": true,`

**Comment by lyndoh** [comment]
Another downstream compilation issue:
If tsconfig.json contains `compilerOptions.strict = true` then compiler will complain about not finding lodash types (unless you already have @types/lodash installed somewhere) eg.
```
node_modules/@cucumber/cucumber/lib/formatter/helpers/event_data_collector.d.ts:2:28 - error TS7016: Could not find a declaration file for module 'lodash'. 'C:/Code/ref-boilerplate-core/node_modules/@cucumber/cucumber/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

2 import { Dictionary } from 'lodash';
```
I think @types/lodash needs to be in cucumbers dependencies instead of devDependencies. Simple workaround in the meantime is to just install @types/lodash in the downstream.

**Comment by davidjgoss** [comment]
Good find `lyndoh` - I don't think we should be relying on the `Dictionary` type for that. I'll try and break that dependency.

**Comment by davidjgoss** [comment]
Addressed by the various linked PRs.
