### ISSUE TITLE
why does cucumber require react for angular app?

### ISSUE THREAD

**Issue by ninjabhishek** [cucumber/cucumber-js#1536]
I am using angular 9 and migrating to 11. V7.0.0 of cucumber seems to have internal chained dependencies requiring react, with some peer dependencies asking for react. Why is that the case when I want to use it in Angular?

Can someone list me down the list of dependencies to have in Angular (all latest) if my question is not really an issue?

**Comment by davidjgoss** [comment]
Thanks for raising @ninjabhishek. This is because our built-in HTML formatter uses React. However, since the formatter is a separate package and bundles React etc via webpack, we should be able to change to a dev dependency without issue.

We'll fix this in a patch release soon; in the meantime this should have no impact on your Angular app.

**Comment by davidjgoss** [comment]
7.1.0 was released today including the fix for this https://www.npmjs.com/package/@cucumber/cucumber/v/7.1.0
