### ISSUE TITLE
Steps counter show wrong values

### ISSUE THREAD

**Issue by Florent-Bouisset** [cucumber/cucumber-js#1579]
Hello, since I upgrade to v7 I have this issue (that I didn't have in v5.1):

The counter on the progress bar when using in combinaison with tags show erroneous max value, and the progress-bar size is also not adapted.

**Step to reproduce:**
By your own:
Run cucumber-js with options: `--format progress-bar --tags <tag>`

**Minimal reproducible example:**
https://github.com/Florent-Bouisset/bug-reproduce-cucumber/
> npm run test

**Expected result:**
When the test is over the progress bar should show 5/5

**Actual result:** 
When the test is over the progress bar show 5/15 
15 is the number of step it should have done without the --tag option.

![image](https://user-images.githubusercontent.com/58945185/107987537-203cdf00-6fc6-11eb-9eb0-3319c56428d2.png)

**Comment by davidjgoss** [comment]
Thanks for the clear repro @Florent-Bouisset, we'll take a look at this.

**Comment by charlierudolph** [comment]
Oh very interesting. Appears this has to do with tags filtering out what pickles are actually run. Appears in https://github.com/cucumber/cucumber-js/commit/fef94dd06f2a261d98d00b3cf63cab3519930e77#diff-110f52e3c367c3dccfe5f61c927b3fead90dc3ae442cdfe2cf57703e158571eb we lost the idea about a pickle being accepted / rejected and thus the progress bar now doesn't have an accurate amount of total steps

**Comment by davidjgoss** [comment]
@charlierudolph to fix this we could make the pickle filter available to the formatter.

Another option might be to base the count on `testCase`s instead of `pickle`s e.g:

```typescript
if (doesHaveValue(envelope.testCase)) {
    this.numberOfSteps += envelope.testCase.testSteps.filter(testStep => doesHaveValue(testStep.pickleStepId)).length
}
```

That would yield the correct count (test steps that aren't from a hook), but it doesn't work at the moment because the timing is wrong - per #1408 `testCase` messages are emitted as we go along the test run, but the progress bar needs to have the count upfront before we start to run things. Could do that refactor after all to solve this?

**Comment by Tol1** [comment]
This bugs me a lot on my custom formatter also. Any progress how to fix this?
