### ISSUE TITLE
String empty value is parse as null

### ISSUE THREAD

**Issue by yopasa94** [cucumber/cucumber-js#1618]
Feature file-->
I should receive a '200' '' response:$/

When(/^I should receive a '(.+)' '(.+)' response:$/, async function (a: string, b: string) {

  }
});

Given the last case, "b" value is set to "null" when a regular expression is defined in the step definition

**Comment by aurelien-reeves** [comment]
Actually, `I should receive a '200' '' response:` does not match `/^I should receive a '(.+)' '(.+)' response:$/`

If you want to make it match, the regexp should look like `/^I should receive a '(.+)' '(.*)' response:$/`

However, did you consider using [cucumber expressions](https://cucumber.io/docs/cucumber/cucumber-expressions/) instead of regexp?

**Comment by yopasa94** [comment]
Thank you !
