### ISSUE TITLE
World.log isn't well documented

### ISSUE THREAD

**Issue by michaelm-rsi** [cucumber/cucumber-js#1864]
**Is your feature request related to a problem? Please describe.**
So if I call this.log("a message") in a step, where does that get output?  After a 2 hour search I haven't found an answer to this simple question.  Finding the answer is made harder by the fact the terms overlap with other cucumber features, particularly the formatters, making it difficult for Google to find the answer. 

**Describe the solution you'd like**
Something in the documentation that describes how to get the log messages created with this.log() to show up in the console or other output.

**Describe alternatives you've considered**
I'm currently using npm's logger, but I want to consolidate reports. To do that I have to understand exactly how the this.log function actually does work.  At this point I'm digging through code to find it, so this issue ticket is largely for those after me.

**Comment by michaelm-rsi** [comment]
This is likely the page that needs to be updated:

https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/attachments.md

That page simply says how to make a log message.  No information is given on how to see those log messages in the console, or in an output file.  The same applies to the attach message.  These commands are useless if not documented fully.

**Comment by michaelm-rsi** [comment]
K, I got this when I deliberately broke a test to see if it would show up then.

`Attachment (text/x.cucumber.log+plain)`

This behavior - that logs only show on failing tests - needs to be documented.

So now to go hunt down the command to get that transformed into my actual message, cause the above isn't useful.

**Comment by davidjgoss** [comment]
It's all related to formatters. `log` is essentially an alias for `attach` with a text MIME type. So what you pass there will become an attachment. Different formatters treat these differently - the terminal ones don't do much with attachments as you've seen. The HTML formatter renders them in the report. Other custom formatters (or services that consume the JSON messages) do their own thing.

In general I would say if you want to specifically log to the console then use `console.log`. You could also override `log` in your custom world and do what makes sense for your project rather than an attachment.

(Yes, this could be documented more clearly.)

**Comment by michaelm-rsi** [comment]
Ok then.  I'll take a stab at getting the documentation on this to be more clear. I'm not the best programmer, but I'm pretty good at docs.

**Comment by davidjgoss** [comment]
Closing as this is in much better shape now, thanks!
