### ISSUE TITLE
Hooks setup in a World are not executed

### ISSUE THREAD

**Issue by rlau89** [cucumber/cucumber-js#1921]
**Describe the bug**
When trying to use an After hook which is set up in a custom World it is never executed. Not sure if this is a bug or a feature request as I can't find docs on if it should or should not be possibile but it would great to have this functional.

Cucumber versions: `8.0.0-rc2` & `7.3.2`

**To Reproduce**
Use a World created like this to run tests.
```
class MyWorld {
  constructor() {
    After(async function() {
      console.log('In teardown')
    })
  }
}

setWorldConstructor(MyWorld)
```

**Expected behavior**
Log statement to be printed

**Desktop (please complete the following information):**
 - OS: macOS 12.2
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by davidjgoss** [comment]
This would not be expected to work, hooks have to be defined upfront and not at scenario runtime.

Can you expand a bit on what problem you’re trying to solve? There’s likely a different way.

**Comment by rlau89** [comment]
I have a custom World which sets up various variables, provides helper functions such as creating users which need to be removed after each scenario. Then this world is created as a lib and imported into other step definition modules. I want the teardown to exist in the custom World so I don't have to repeat code in various places.

**Comment by davidjgoss** [comment]
Okay, thanks for that. I would add your complex teardown as a method on your world:

```js
class MyWorld {
  async teardown() {
    // all the stuff
  }
}
```

Then call it from a hook:

```js
After(async function() {
  await this.teardown()
})
```

That hook could be in each of your projects, or you could include it in your shared library and include it in your list of `require`s on the cucumber-js command.

I'm going to close this issue since the original ask - declaring hooks from a world constructor - isn't something we'd add, but if you want to talk more about solving this need feel free to jump into the [support channels](https://cucumber.io/tools/cucumber-open/support/) (Slack is best). Thanks!

**Comment by rlau89** [comment]
Thanks @davidjgoss I'll work with a solution like this
