### ISSUE TITLE
before a feature and after a feature

### ISSUE THREAD

**Issue by NarcisoCode** [cucumber/cucumber-js#1953]
### 🤔 What is the problem you have observed?

I understand that the before a feature and after a feature would affect the parallel execution of a cumulative project because I understand that the parallel execution is done per scenario, but this means that projects that use different integrations (api tests, verifications to database and ui tests) in their bdd tests they consume a lot of resources because we do not have the option to choose whether the parallel execution is carried out by scenario or feature. they think that. Can it be added as an option?

**Comment by davidjgoss** [comment]
Hooks on a feature level is not something we're going to do.

> the parallel execution is done per scenario

Really _all_ execution is done per scenario - the concept of features is really just logical grouping and not something that's considered at run time.

From your comment you might be interested in the [custom assignment functionality](https://github.com/cucumber/cucumber-js/pull/1588) that's due to be released soon, which will allow control over how scenarios are allocated to workers when running in parallel.
