### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [cucumber/cucumber-js#1961]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by aslakhellesoy** [comment]
The Cucumber community stands with Ukraine. SmartBear, the primary supporter of Cucumber, has taken a number of actions including financial support for refugee programs.

**Comment by id-dan** [comment]
thank you, @aslakhellesoy 
Could you pls also add "StandwithUkraine" banner on cucumber repo? it will inform people, how they can help for us

**Comment by mattwynne** [comment]
Thanks your work on this campaign and for this to our attention @id-dan. Best of luck to you, your friends and family ❤️

**Comment by id-dan** [comment]
Thank you, guys!!! You make big deal 👍

**Comment by Gertrido** [comment]
A disgusting decision to block access to CloudFront. Well, forking is the only solution, "open" source for ordinary developers will not be the same.

**Comment by aslakhellesoy** [comment]
We have decided to block traffic from Russia and Belarus to the [cucumber.io](http://cucumber.io/) domain until further notice. We're sorry for the inconvenience this causes for individuals residing in these countries. Because of the sensitivity of this topic this issue has been closed for further comments.
