### ISSUE TITLE
dependencies vulnerability CVE-2021-3807

### ISSUE THREAD

**Issue by 1323** [cucumber/cucumber-js#2109]
### 🤔 What's the problem you've observed?

The ansi-regex module has following vulnerability https://www.cve.org/CVERecord?id=CVE-2021-3807

### ✨ Do you have a proposal for making it better?

Updating the package "has-ansi": "^4.0.1" dependency for version [5.0.1 ](https://github.com/chalk/has-ansi/releases/tag/v5.0.1) where this issue was addressed

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by davidjgoss** [comment]
Thanks for raising @1323. An upgrade of `has-ansi` is the right thing to do, unfortunately that's non-trivial at the moment because that package has gone ESM-only and Cucumber isn't.

I noticed this in the release notes of `ansi-regex`, where the underlying issues was fixed:

> You are only really affected if you run the regex on untrusted user input in a server context, which it's very unlikely anyone is doing, since this regex is mainly used in command-line tools.

So I'm not _too_ concerned about this in the short term, but I'll see if there's something we can do.
