### ISSUE TITLE
Malware in dependency lib

### ISSUE THREAD

**Issue by m-s-c-h** [cucumber/cucumber-js#2160]
### 👓 What did you see?

Cucumber has a dependency to the [es5-ext library](https://github.com/medikoo/es5-ext) (@cucumber/cucumber -> duration -> d -> es5-ext).
Since march 2022, the es5-ext library contains a malware defined as protestware.
[Issue 186](https://github.com/medikoo/es5-ext/issues/186) has been filed for the library es5-ext but is still open.

### ✅ What did you expect to see?

Dependencies free of malware / protestware.
If bound to policies that prohibit any kind of malware and protestware, you are in trouble.

### 📦 Which tool/library version are you using?

Cucumber 8.3.1

### 🔬 How could we reproduce it?

1. Install Cucumber version 8.3.1
2. After _npm install_ see file [_postinstall.js](https://github.com/medikoo/es5-ext/blob/main/_postinstall.js) in _node_module/es5-ext_ folder

**Comment by davidjgoss** [comment]
Thanks for raising @m-s-c-h. It’s a tricky one in terms of policy as (speaking only for myself) I support the principle but it’s not the way I would choose to communicate.

However we can nearly skirt the issue because I’m planning on refactoring out the durations library anyway. I’ll use this issue as a vehicle for that.

cc @mattwynne for visibility

**Comment by unional** [comment]
If you want a remedy to the problem, you can use the `overrides` mechanism of your package manager of choice.

I have created a video to describe what you need to do: https://youtu.be/dh9UUqsJLok

**Comment by m-s-c-h** [comment]
Many thanks @davidjgoss and @unional!!! In the short run, the override mechanism helps us. And the refactoring sounds great for the long run.
