### ISSUE TITLE
html formatter ignores attachments of examples

### ISSUE THREAD

**Issue by zbirizdo** [cucumber/cucumber-js#2242]
### 👓 What did you see?

When I attach images to html report (build in html formatter) and I use examples in my scenarios only the first examples's image show up in the report, the others gets ignored.

### ✅ What did you expect to see?

I expect to see attachments, no matter which example I attach them.

### 📦 Which tool/library version are you using?

    "@cucumber/cucumber": "7.3.2",
    "@cucumber/html-formatter": "17.0.0",

### 🔬 How could we reproduce it?

Create a scenario with multiple examples and set up the After hook to attach an image to each.

### 📚 Any additional context?

Here I have a scenario with multiple examples. The third one fails and there is no attachment:
![image](https://user-images.githubusercontent.com/473723/218345054-ddcd8833-ec82-43c3-ba02-163edbf7a252.png)

When I reorder the examples to be the first one that fails I get the attachement:
![image](https://user-images.githubusercontent.com/473723/218345180-5b596f1f-c6af-49a8-beb7-47ea830c0dc1.png)

**Comment by davidjgoss** [comment]
Please upgrade to the latest `@cucumber/cucumber` (8.11.1 at time of writing) and also remove your dependency on `@cucumber/html-formatter` - you don't need to depend on that yourself because Cucumber brings the correct version in.

In newer versions, you can click on any of the rows in the example table to go through and see attachment/error details for each step.
