### ISSUE TITLE
ci: adding gitpod.yml file

### ISSUE THREAD

**Issue by Ananya2001-an** [cucumber/cucumber-js#2254]
### 🤔 What's the problem you've observed?
There are many contributors who prefer developing using cloud services like Gitpod. 

### ✨ Do you have a proposal for making it better?
We can add a gitpod.yml file that will run the prebuild tasks like installing all dependencies and running tests automatically as soon as user launches a new workspace.

### 📚 Any additional context?
I would like to work on this.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by Izhaki** [comment]
Sorry, but it isn't clear what is being proposed here.

Where should `gitpod.yml` be added? Which tests will be running?

**Comment by Ananya2001-an** [comment]
It will be added in the root. Something like this:
```

tasks:
  - init: npm install
    command: |
     npm run test

```

According to contribution guide users have to do both these things before they can start hacking. So it’s better to create this file for gitpod users so that they don’t forget to run the tests and check if everything is working fine.

**Comment by Izhaki** [comment]
Just let me sure I got this right: The proposal is to add `gitpod.yml` to this repository, so people who prefer to use GitPod instead of cloning and using their machines have slightly better integration?

A few questions:

1. How should we deal with the blow-up number of similar platforms (GitHub's Codespaces, Codesandbox, are barely a start)? If we are to add support to each we are going to end up with a lot of 3rd party related files in this repo.
2. GitPod does not require `gitpod.yml` - users can just run the `install` and `test` scripts manually. Correct?
3. In what way the developer experience be downgraded if we do not add this file? Two more clicks in GitPod?

The main concern here is that there is no end for these sort of add-ons and more often than not such files add noise (and could involve maintainability); so it pays to stick to things that are essential or indisputably popular.

I would suggest to close this for now, but if upvoted by, say, more than 50 users we shall add it.

**Comment by Ananya2001-an** [comment]
I understand. I will close it.
