### ISSUE TITLE
Integrate cucumber-html in cucumber-js

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#28]
A new project has been created for [html reporting](https://github.com/cucumber/cucumber-html) for all cucumber implementations. Make cucumber.js use it.

There is already a [proof-of-concept](http://cucumber-js-html.herokuapp.com/).

Basically, cucumber-js needs a new listener that will pass translated events to the cucumber-html formatter and reporter.

**Comment by h2non** [comment]
There are plans to support/integrate it soon?

**Comment by bailejl** [comment]
@jlin412 I am using protractor with Cucumber, so I would like it added to Cucumber.

**Comment by goriol** [comment]
I am also interested by an HTML formatter and as this issue is still open, I tried to implement one. Adding a new formatter is pretty easy but I am now stuck with the cucumber-html integration.

Basically, what I wanted to do is something like that:
https://gist.github.com/goriol/f1bed747658e2a27f4c0.js

But cucumber-html complains jQuery is not defined...
Could you help me a little bit with this integration.

**Comment by JimTheMan** [comment]
How can we use cucumber-html with cucumber.js to generate reports?

**Comment by gkushang** [comment]
Hi Guys, checkout the [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) for HTML reporting. Converts JSON to HTML reports. Here is the snapshot of it's bootstrap theme,

![screen shot 2016-06-27 at 11 19 12 am](https://cloud.githubusercontent.com/assets/3663389/16391556/b427306e-3c75-11e6-93b1-2add653b6cba.png)


@jbpros Hi Julien - How about to make this an official module of cucumber-js project? Can you check it out? It will be great to be one of the HTML formatter.

**Comment by jlin412** [comment]
Just trying it out.  It is pretty nice.

**Comment by charlierudolph** [comment]
Closing as duplicated of #94
