### ISSUE TITLE
failure in AfterStep RegisterHandler stop cucumber from execution

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-js#295]
This is a followed up issue from https://github.com/angular/protractor/issues/876
I add a protractor code in the registerHandler('AfterStep').  It failed due to unexpected network/api issue (unexpected alert open) but it stop the test completely with the error message:
[launcher] Process exited with error code 1.  

Is this an expected behavior?  If it is, I think that we need more info on error message so it will be easily to debug.  If not, we should continue to test flow without exiting the cucumber.

``` javascript
  this.registerHandler('AfterStep', function (event, done) {
    var commonPage = new pages.CommonPage();
    browser.ignoreSynchronization = true;
    commonPage.waitForOverlay().then(done);
  });
```

**Comment by jbpros** [comment]
I *think* this is purely protractor-related and I *think* it's protractor's fault if the process stops.

What if you call back (`done()`) without passing any error even if the promise is rejected? Does it still stops the whole process?

**Comment by jlin412** [comment]
@jbpros Can you give a clear code example so I can try?

**Comment by jbpros** [comment]
Something along those lines I guess:

```javascript
this.registerHandler('AfterStep', function (event, done) {
  var commonPage = new pages.CommonPage();
  browser.ignoreSynchronization = true;
  commonPage.waitForOverlay().then(done, function (_) { done(); });
});
```

**Comment by jlin412** [comment]
@jbpros I tried it and it fixed the issue.  (The error message is given and test continue)  What type of wizardry is this?  Is this a bug in Protractor?

**Comment by jbpros** [comment]
What this code does is handle both success and failure cases. When it's failing, it's calling back Cucumber as if everything went smooth. If you don't pass a second function to `then()`, failure will bubble up and get caught by Protractor.

Because of the way Protractor wraps Cucumber, it will catch the error before Cucumber gets a chance. That's why Protractor fails the whole thing instead of letting Cucumber fail that scenario and moving on to the next one.
