### ISSUE TITLE
Add .hash method to DataTable objects

### ISSUE THREAD

**Issue by ExplodingCabbage** [cucumber/cucumber-js#302]
Currently, they expose `.rows()` and `.hashes()`, but both of these return an array. If I'm using a data table to represent a key-value mapping, like

    Feature: Tables as objects
        Scenario: I want to represent myself as a table
            Given I have the following properties
                | color | light pink  |
                | size  | fat         |
                | age   | 24          |
                | name  | mark        |
                | job   | code monkey |
            Then I should be able to get myself in my step definition as an object mapping properties to values

then neither of these is convenient.

The Java API for Cucumber seems to support this - see 'Map of Scalar' at https://cukes.info/step-definitions.html#map_of_scalar. Can the JS version support it too, perhaps as a `.hash()` method?

As an aside, I'd've been able to add this from userland if `Cucumber.Ast.DataTable` were implemented as a proper constructor that were invoked with `new`, rather than just a function that creates an object and returns it. I'm not sure if the decision to implement things the way they are is a carefully considered style decision to deliberately prevent prototype changes being made from userland, or if this just wasn't thought about?

**Comment by jbpros** [comment]
Yes, we need `rowsHash()` (same as ruby's [`rows_hash`](http://www.ruby-doc.org/gems/docs/d/davidtrogers-cucumber-0.6.2/Cucumber/Ast/Table.html#method-i-rows_hash)). PR welcome!

The choice of closure-based constructors is not primarily targeting prototype tempering from userland but it's kind of a nice side-effect as it forces you to open this issue and add the missing behaviour to master. ;)

That being said, it's still possible to wrap the whole `DataTable` constructor so that augmented objects are returned. You might also want to consider `raw()` to get the original table data and transform it to a hash (but please, share your code with us!).

**Comment by cades** [comment]
Any progress on this PR?

**Comment by jbpros** [comment]
Closed by #304.
