### ISSUE TITLE
Please add support for TypeScript

### ISSUE THREAD

**Issue by Chris2011** [cucumber/cucumber-js#335]
I created a lib with typescript and my tests are written in typescript too. I really would like to try cucumber.js and create step definition files, with typescript. So you support coffeescript and js, .ts would be nice too.

Regards

Chris

**Comment by aslakhellesoy** [comment]
Why don't you send a pull request @Chris2011

**Comment by Chris2011** [comment]
I will be only a customer of this project, when I do each pull request of each stuff what I use and there is some missing, than I can create it by my own. It is only a feature request. If someone has time and would like to do it, why not. Me not, because I don't have time, I have the same normal work and other projects and don't want to be a contributor on each project that I use. Sry for the harsh words maybe but for me it is clear that it is not possible to be a contributor on each project, what I use. I have to understand the source and so on.

**Comment by aslakhellesoy** [comment]
I understand @Chris2011. Maybe one day someone will decide to spend time implementing this because they want to help you, or just for fun.

The more realistic scenario is that this feature request stays open until someone needs it enough to be willing to spend the time and effort to implement it and send a PR.

**Comment by Chris2011** [comment]
Maybe. Thx for your opinion. In my perspective, it was only logic to ask for this feature because TS will be more popular as for 1 or 2 years. And when you or whoever decided to implement coffeescript too, why not typescript too?

Thx a lot. We will see what happens...

**Comment by jbpros** [comment]
In general - just like formatters - I'd like to have language/dialect support to be 3rd party plugins instead of part of the core (including the current CoffeeScript and PogoScript).

**Comment by ruslango** [comment]
TS +1

**Comment by laland** [comment]
+1

**Comment by RokaFogtaCsukaFarka** [comment]
Like it, pls do it some time!!!

**Comment by AbraaoAlves** [comment]
:+1:

**Comment by aslakhellesoy** [comment]
No amount of +1 or :+1: will make this happen. Someone has to submit a pull request.

**Comment by samccone** [comment]
:+1: @aslakhellesoy spot on

**Comment by aslakhellesoy** [comment]
:8ball: @samccone

**Comment by mkusher** [comment]
@jbpros @aslakhellesoy the only thing should be done to support 3rd party languages is implementing way to modify:
```javascript
SupportCodePathExpander.SUPPORT_CODE_FILES_IN_DIR_REGEXP = /\.(js|coffee|pogo)$/;
```
And then anyone can register any transpiler in `support/env.js` for example
maybe this regex should be removed at all?

**Comment by SeanFarrow** [comment]
I'm happy to look at this. I can find the coffeeScript feature file but can't find where the step definitions are implemented, please could someone give me some pointers as to what needs to be done?

**Comment by mkusher** [comment]
@SeanFarrow I've already done it locally. You have just to modify `/lib/cucumber//cli/argument_parser/support_code_path_expander.js:12` and then add any transpiler via require hook

**Comment by SeanFarrow** [comment]
Are you ghoing to send a pr?

**Comment by jbpros** [comment]
@mkusher there is more to it. To be complete, step definitions snippets should also be available in the additional language (which is currently not done for PogoScript), see the CLI `--coffee` flag.

I'd really like this to be done via a plugin/transpiler system anyway and remove all dialects from core (including coffeescript).

**Comment by henrify** [comment]
I don't understand why language specific support is even needed? Wouldn't you just transpile the step definitions to JavaScript as part of your build process?

**Comment by charlierudolph** [comment]
#398 should make supporting any transpiler simple

**Comment by jbpros** [comment]
Yep, #398 will fix this.

@henrify the only thing that "needs" to be added to Cucumber is the step definition snippet support for other languages. Currently they're in vanilla JS by default and can be output in CS with the `--coffee` CLI flag. 

We might just drop non-JS snippets altogether (including CS?). Thoughts?

**Comment by jbpros** [comment]
#398 has been merged and will be available in the next release. TypeScript support is [documented in the README](https://github.com/cucumber/cucumber-js#typescript).

**Comment by JoshuaKGoldberg** [comment]
@jbpros since the readme's been updated, and this shows prominently in results for `"cucumber typescript"`, an excerpt:

### Transpilers
 
 -Step definitions and support files can be written in other languages that transpile to javascript.
 -This done with the CLI option `--compiler <file_extension>:<module_name>`. For CoffeeScript 1.10.0,
 -this is done with `--compiler coffee:coffee-script/register`.
Step definitions and support files can be written in other languages that transpile to javascript. This done with the CLI option `--compiler <file_extension>:<module_name>`.

#### CoffeeScript

Install the [coffee-script](https://www.npmjs.com/package/coffee-script) NPM package and invoke Cucumber with `--compiler coffee:coffee-script/register`.

#### TypeScript

Install the [typescript-node](https://www.npmjs.com/package/typescript-node) NPM package and invoke Cucumber with `--compiler ts:typescript-node/register`.

As usual, all your step definition and support files must export a function to be run by Cucumber. This is how it is done in TS:


```typescript
declare var module: any;
module.exports = function () {
 this.Given(/.*/, function () {
   // ...
 })
}
```

#### PogoScript

Install the [pogo](https://www.npmjs.com/package/pogo) NPM package and invoke Cucumber with `--compiler pogo:pogo`.

**Comment by Chris2011** [comment]
Is it really needed to use typescript-node? Is it possible to use the official supported tsc instead of typescript-node? I don't know the differences but tsc is official supported from Microsoft.

**Comment by mkusher** [comment]
@Chris2011 `ts-node` is just a register hook for node.js that will run compilation via tsc

**Comment by Chris2011** [comment]
Ok thx.

**Comment by TimMurphy** [comment]
@JoshuaKGoldberg where is the excerpt from? My searches have failed to find it.

**Comment by mkusher** [comment]
@TimMurphy https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#transpilers

**Comment by AbraaoAlves** [comment]
A sample to guide using cucumberjs with typescript:
https://github.com/AbraaoAlves/cucumber-protractor-typescript-boilerplate

**Comment by jlamandecap** [comment]
Thanks @AbraaoAlves for the sample.
Unfortunately, it only works with cucumberjs 1. The protractor-cucumber-framework layer is not compatible with the cucumber2 rcs.

**Comment by Rajazpandi** [comment]
how to attach screenshot in cucumber report. I'm using typescript language. Please anyone help me.

**Comment by Raghunandanr76** [comment]
Please confirm if there would be  cucumber+Protractor+Typescript compatibility issues going forward...as we plan use the combination for our implementations..

**Comment by arjunjh10** [comment]
@Rajazpandi 
Do something like this in `After`
```
driver.takeScreenshot().then(data => {
        attach(new Buffer(data, 'base64'), 'image/png');
      }).catch(error => {
        info(error);
        throw error;
      });
```
