### ISSUE TITLE
async step returning a promise

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#367]
If a step takes a callback and returns a promise multiple instances of cucumber-js end up running.
The return value of the step should be ignored if it the step takes a callback.

**Comment by charlierudolph** [comment]
Appears this change introduced it. https://github.com/cucumber/cucumber-js/commit/b138589f347bc21d12eca37277e55a7a6a1baf08

**Comment by charlierudolph** [comment]
In my use case I am doing async callbacks but using a promise based library (selenium-webdriver) so I ended up returning a promise without meaning to. I'd rather not need to insert a bunch of extra statements to prevent me from returning a promise.

**Comment by jbpros** [comment]
This is not good. Since #359 has been merged, people using coffeescript (and its implicit returns) or ES6 arrow functions will most likely run into issues when using promise-based libs.

I'm thinking reverting #359. 

@zs-zs I understand why you need that relaxed callback/promise check in your lib. What about a configuration option to tell Cucumber to relax its checks? Or a method on `this` (support code helper) to tell Cucumber to not check the number of params in the stepdef function:

```javascript
// features/step_definitions/my_steps.js
module.exports = function () {
  this.relaxStepDefinitionCallbackCheck(true);

  this.Given(...
}```

**Comment by charlierudolph** [comment]
@zs-zs any thoughts? I really want to revert #359. Can you give more explanation as to why you are using are using implicit parameters? 

Instead of relaxing the check, I'd prefer cucumber-js actually tighten it and fail a step definitions if it doesn't have the correct number of arguments (either exactly matching the number of arguments it will pass, or having that number plus 1 to account for the callback)

**Comment by janmeier** [comment]
Took me some time to figure this out! 

Definitely a +1 from me on more strict checking, so that an error is thrown in a step takes a callback put returns a then-able.
