### ISSUE TITLE
registerHandler

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#388]
This isn't well documented, what exactly is the event thats passed?

Also it would be great if this could synchronous and work with returning a promise in order to be consistent with steps and other hooks.

**Comment by jbpros** [comment]
`registerHandler()` isn't documented because it's an experimental thing. It's basically a shortcut to the listener API (which needs better doc as well). I'm not sure it'll stay in forever, especially once we've consolidated the plugin API (which is most likely going to be based on the listener API).

The event is an instance of the AST tree walker [event](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/runtime/ast_tree_walker/event.js).

Regarding the sync/promise support, I assume you're not talking about `registerHandler` but the handler it receives. This is a lower-level API and I'm not comfortable at this stage to support different form of flow control in it. The recent sync/promise support in step definitions has led to [some issues](https://github.com/cucumber/cucumber-js/issues/367#issuecomment-125872895) I don't want to see in the listener API.
