### ISSUE TITLE
Capture Optional Args does not work

### ISSUE THREAD

**Issue by gkushang** [cucumber/cucumber-js#392]
```
this.Then(/^User (attempts to login (\d+) times with invalid credentials|is asked to enter captcha for (\d+) invalid login attempts)$/,
		function(numberOfAttempts, alternative, whatsThis, callback) {
}
```

Above function works but with 4 parameters and "whatsThis" is undefined. I expected to be a "callback" as a third arguments but its really a 4th Arg. Why it expect to have 4 arguments?

**Comment by gkushang** [comment]
BTW - this works fine

```
this.Then(/^User (?:attempts to login|is asked to enter captcha for) (\d+) (?:times with invalid credentials|invalid login attempts)$/,
		function (numberOfAttempts, callback) {
```

**Comment by jbpros** [comment]
The number of matching groups is always fixed for a given regexp. Even if a matching group isn't matched, it will be part of the params. That makes actual sense as working otherwise would render the param count variable, which would be a nightmare to handle in our stepdef signatures.

`(attempts to login (\d+) times with invalid credentials|is asked to enter captcha for (\d+) invalid login attempts)` is group 1 (param 1)
`(\d+)` is group 2 from sub expression `attempts to login (\d+) times with invalid credentials` (param 2) 
`(\d+)` is group 3 from sub expression `is asked to enter captcha for (\d+) invalid login attempts` (param 3)

This means one of param 2 and 3 will always be undefined in your step definition.

And yes `(?:...)` lets you avoid capturing a group.
