### ISSUE TITLE
Add tag treshold

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#43]

**Comment by mlarcher** [comment]
any intent on implementing this feature ? That could get quite useful

**Comment by aslakhellesoy** [comment]
-1. This belongs in Gherkin-Lint. See discussion in gitter: cucumber/contributors

**Comment by mlarcher** [comment]
during development, we often use @only or @wip tags to isolate tests we're currently working on. 

In other implementations of cucumber, `cucumber --tags ~@wip && cucumber --wip --tags @wip` can be used in pre-push hook to prevent those tags from being pushed when work is done.

cucumber-js doesn't seem to provide either of those features. 
What approach would you recommend for that scenario if those features aren't to be implemented ?

**Comment by charlierudolph** [comment]
> cucumber-js doesn't seem to provide either of those features.

Which features exactly? Yes it does not support tag threshold and I don't see the reason to do so. Instead of `@only` you can run scenarios by file path and line number. I also don't like the `--wip` flag on cucumber-ruby as it encourages adding failing scenarios to your codebase.

**Comment by mlarcher** [comment]
I see your point.
I find running scenarios by filepath:linenumber or by name less practical than simply using an @only tag, though. I've resorted to using text parsing to make sure there is no stray @only during git pre-push hook.

**Comment by charlierudolph** [comment]
Using `filepath:linenumber` is the most efficient as it will only load and parse that specific feature instead of all of them. It also prevents this need to edit the gherkin when you don't need to.

I agree that sometimes specifying the full path to a feature can be a bit painful if you have a lot of features that are nested in folders. A tool I just started using is [tertestrial](https://github.com/Originate/tertestrial-server) which allows you to trigger a specific test from your editor. Thus instead of adding @only above the particular scenario, you can just trigger the test for it.

Sounds like you have a workaround for now. I like the idea of this being in a linter or a pre hook as you have it.
