### ISSUE TITLE
Question: Why are Given, Then, When aliases?

### ISSUE THREAD

**Issue by hypesystem** [cucumber/cucumber-js#453]
Take an example:

    Given my cat's name is "Frank"
    When I change my cat's name to "James"
    Then my cat's name is "James"

When I implement these steps, the step definition `this.Given(/^my cat's name is "([^"]+)"$/, ...` matches both the Given and Then cases above (because the regex matches both cases).

Why are the `Given` and `Then` steps not unique in category? Why is a `Given` step allowed to match a `Then` step? A `Then` should always verify some state, whereas `Given` ensures it is as described --- very different actions.

**Comment by charlierudolph** [comment]
@aslakhellesoy @jbpros can you weigh in here? I just know that cucumber treats Given / When / Then the same but don't know why.

**Comment by jbpros** [comment]
Not tying step definitions to specific keywords reduce the risks of ambiguity, especially when reusing them in several scenarios because this "constraint" forces us to use a slightly different language - or rather tense - in different categories of steps. 

* Givens describe context. Things that happened in the past and still hold true. You generally express them with a past or present tense (*Given my cat's name is "Frank"* is something that was set in the past and still holds true; *Given my cat was named "Frank"* is another way of expressing this).
* Whens describe actions or events trigger now. They're generally immediate but can last longer, but they're not part of the previous context; they will change the context. They're generally expressed with the simple present tense.
* Thens describe expectations, outcomes, the resulting context after the actions were taken against the initial context. To express that expectative aspect (and make a clear difference with Given steps using present tense), it's often recommended to use the word "should" in them: *Then my cat's name should be "James"*.

Once you start following those "rules", you'll never need the same sentence in different sorts of steps anymore. The way Cucumber doesn't make any distinction between keywords will then actually help you stick to those rules.

I highly recommend Liz Keogh's [blogpost](http://lizkeogh.com/2014/09/02/a-little-tense/) on this, it's really good.

PS: Please use the [cukes group](https://groups.google.com/forum/#!forum/cukes) for this kind of question in the future. This is an issue tracker for Cucumber.js.

**Comment by hypesystem** [comment]
Thanks for the answer :) I didn't know if this was cucumber-js specific or general to cucumber, hence I asked the question here.

**Comment by jbpros** [comment]
No worries, feel free to pursue the discussion on the group.
