### ISSUE TITLE
cucumber.yml

### ISSUE THREAD

**Issue by kevgo** [cucumber/cucumber-js#485]
The [cucumber.yml](https://github.com/cucumber/cucumber/wiki/cucumber.yml) file allows to provide configuration options to be always used. This is especially useful for Cucumber.js for example when writing step definitions in a transpiled language.

**Comment by jbpros** [comment]
The file is called `cucumber.js` instead of cucumber-ruby's `cucumber.yml`. This is already supported but poorly documented.

Have a look at [features/profiles.feature](https://github.com/cucumber/cucumber-js/blob/master/features/profiles.feature).

@charlierudolph could you document this in the README?

**Comment by kevgo** [comment]
Thanks @jbpros, this is awesome!
