### ISSUE TITLE
Maximum call stack exceeded on dry run

### ISSUE THREAD

**Issue by jbpros** [cucumber/cucumber-js#496]
When running cucumber.js's own suite with dry run:

```
nerwen:cucumber-js jbpros$ cucumber.js -f progress --dry-run 
---------------------------------------------------------------------------------------------------------/Users/jbpros/Projects/cucumber-js/lib/cucumber/support_code/step_definition.js:56
      return regexp.test(stepName);
                    ^

RangeError: Maximum call stack size exceeded
    at RegExp.test (native)
    at Array.filter (native)
```

**Comment by jlin412** [comment]
+1

**Comment by charlierudolph** [comment]
So this doesn't appear to be caused by an infinite loop but solely based on how cucumber-js is internally using an asynchornous callback api everywhere but executes the callback synchronously when in dry-run. This could hypothetically occur in a big test suite where all step definitions are synchronous.

I was able to prevent the stack overflow by just wrapping the contents of [processStep in ast_tree_walker.js](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/runtime/ast_tree_walker.js#L232) with a setTimeout. Not a big fan of doing that but I guess it does make some sense as executing a step can be asynchronous, we need to force it to always be asynchronous.

@jbpros any thoughts?

**Comment by Asuza** [comment]
I'm experiencing what I believe is the same issue on my test sweet (not during a dry run). This is bad news for me because I still have a lot more tests to write.

If I run `cucumber.js --dry-run` everything seems to work. The result summary looks like this:
```
40 scenarios (40 skipped)
144 steps (144 skipped)
0m00.000s
```

When I run the test suite via `cucumber.js`, I get several errors:
```

    Scenario: Value below the minimum length is invalid
        When I pass "setMinLength" the value 20
        And I pass "setValue" the value "Too short to ride."
        And run "validate"
        Then the result is false
```
Not only that, but the summary has different numbers than during the dry run.
```
43 scenarios (4 failed, 39 passed)
148 steps (4 failed, 2 skipped, 142 passed)
0m00.046s
```
The real test run contains more scenarios and steps than the dry run? I don't know if that's related to the errors or not, but seems worth noting.

I'm going to attempt the workaround that @charlierudolph suggests and hope for the best.

**Comment by Asuza** [comment]
Thanks for the solution, @charlierudolph. It worked great. I was looking at attempting to fix the problem in a different way and stumbled across this article about Trampolines. I have to wrap my head around it, but it might prove useful to whoever ends up fixing this bug: http://raganwald.com/2013/03/28/trampolines-in-javascript.html
