### ISSUE TITLE
Support organizing .feature files into subdirectories of "features"

### ISSUE THREAD

**Issue by kevgo** [cucumber/cucumber-js#515]
Cucumber-Ruby allows to organize `.feature` files into subdirectories of `/features`. This structure is useful for example when using folders for epics, and then one `feature` file per feature of that epic. 

Cucumber-JS doesn't seem to support this fully. 
* running `cucumber-js features/run.feature` works
* running `cucumber-js features/test/run.feature` fails because it doesn't find the step definitions 

Both `run.feature` files are identical.

**Comment by jlin412** [comment]
It works for me.  I think that it has to do with how you require step
definitions

**Comment by charlierudolph** [comment]
@kevgo you just need to add a `-r features` to load all the support files in the features directory. By default, cucumber loads all support files in the parent directory of the feature or features you are running (I believe this is what cucumber-ruby does as well), which is why it doesn't work for nested features out of the box.

@jbpros @aslakhellesoy thoughts on making this more automatic and if the feature path includes a `features` folder then use it instead of the parent directory of the feature?

**Comment by kevgo** [comment]
Thanks, that fixes it! And +1 on @charlierudolph's idea. I think it's a reasonable convention to make the top-most `features` folder in the current path the one that contains the support files. At least in the absence of data that configures the system otherwise...
