### ISSUE TITLE
Use of cucumber with a date/time mock library?

### ISSUE THREAD

**Issue by pke** [cucumber/cucumber-js#535]
Is that against the original philosophy of cucumber?
In my app I have several features that take a while before they emerge. Like

`When the app runs for 10 minutes`

Certainly the step should not really wait 10 minutes. Instead I hope a time/date mocking library could be used to speed up the wait time?

Something like https://github.com/plaa/TimeShift-js it even mentions cucumber steps.

**Comment by charlierudolph** [comment]
Hmm, I personally have never had to write a line like that. What in your code takes 10 minutes? If you just need something that was created ten minutes ago, the step could be "Given x happened 10 minutes ago", where you create something and set its created timestamp in the past

**Comment by pke** [comment]
Its for an onboarding experience in an app. I am not sure I will have the ability to just set the apps start time to any value, since its driven by redux-saga which allows you to write code like

`yield wait(10, "minutes")`

Maybe I ask over there how this could be solved.

**Comment by charlierudolph** [comment]
This would also be hard for cucumber-js as we use the date object for timing how long each step is running for (in browsers at least, we use process.hrtime in node)

**Comment by mjhm** [comment]
We ran into this while naively trying to use `sinon.useFakeTimers`.  Our use case is to simulate timeouts of bearer tokens in a user authentication flow. Apparently cucumber-js internally uses `setTimeout` and `clearTimeout`, and therefore picks up the monkey patched fakeTimer versions of those functions.  This causes the test to hang forever because time stands still while sinon is in control.

**Comment by pke** [comment]
Very cool, thanks.
