### ISSUE TITLE
Save more than one screenshot per Scenario / Name screenshot (feature request)

### ISSUE THREAD

**Issue by hawthorner** [cucumber/cucumber-js#579]
Hi

It seems that when we attach more than one screenshot in during a scenario, only one actually gets saved, presumably it overwrites the previous ones as it's the last one attached that survives.

Would it be possible to save multiple screen-shots during a scenario and give them custom names?  Or is it already possible and I am missing it or doing something daft?

Thanks for your time.

**Comment by charlierudolph** [comment]
Can you please provide the code you used to attach the screenshot with enough details to be able to reproduce the issue?

**Comment by charlierudolph** [comment]
@hawthorner any update on this? I need more information in order to help with this issue.

**Comment by hawthorner** [comment]
Deepest apologies about not getting back to you on this.  
Unfortunately the project I used this on closed unexpectedly and I have been unable to fetch the code.  If it is not an issue anyone else has mentioned then likely I just did something wrong.  Either way we are probably best just closing this.  Sorry for the time waste.

**Comment by aluzardo** [comment]
Same problem here I want to save more than one screenshot but it is not possible because the screenshot are overwriting with same name.

Is it possible custom the name using a timestamp?

It is a big issue for me because I have a lot of reports but only the last report have the correct screenshots.

**Comment by charlierudolph** [comment]
Can you please provide a minimal but reproducible example?

Each call to `attach` appends an item to an array so anything that is attached should not be overwriting the previous.

**Comment by aluzardo** [comment]
The problem is because if you store reports in the same folder the very last screenshots always overwrite the previous one. 

I used a workaround to fix it. I am storing the reports in different folders. One folder for each report but I would like keep all reports in the same folder.

This is one example of all my reports when I am storing in the same folder. You can see that I have only 8 screenshots but I should have hundreds. They always use the same name and I would like use a timestamp on the name.

![screen shot 2017-03-07 at 10 11 55](https://cloud.githubusercontent.com/assets/11529571/23649380/8e1ed528-031e-11e7-95d4-88eedb664ef1.png)

**Comment by hawthorner** [comment]
Hi,
Yeah that's pretty much exactly the same issue I had and the same approach to solving it with lots of folders, but I couldn't post a code example as the project was frozen.  At the time nobody else seemed to have the issue, so I presumed it was an error with the way I did things.
