### ISSUE TITLE
--compiler option always exits with status code 0

### ISSUE THREAD

**Issue by dueckes** [cucumber/cucumber-js#598]
Version: 1.0.0
Node: 4.3.2

When executing:
`cucumber-js -f pretty --compiler=js:babel-register`

I'm always receiving an exit code of 0, regardless of test failure.

Perhaps there's another option required to preserve the appropriate exit code?

**Comment by charlierudolph** [comment]
the compiler option should have no effect on the exit status. Can you provide a minimal project setup (files + their content) that I can use to reproduce the issue?

**Comment by dueckes** [comment]
See:
- [Codebase with a trivial failing scenario](https://github.com/MYOB-Technology/cucumber-js-selenium-webdriver-example/tree/failing_scenario)
- [Travis build result](https://travis-ci.org/MYOB-Technology/cucumber-js-selenium-webdriver-example/builds/139776978) - note that the exit code is still 0.

**Comment by charlierudolph** [comment]
This issue is actually [here](https://github.com/MYOB-Technology/cucumber-js-selenium-webdriver-example/blob/failing_scenario/features/support/hooks.js#L19) and is already documented by #487. When using registerHandler you are always passed a callback and cannot use the other interfaces (generators / promises / synchronous). Its an annoying inconsistency caused by the fact that registerHandler is just a cucumber internal that was exposed.

**Comment by charlierudolph** [comment]
#487 has been closed. Please try running with version 1.1.0

**Comment by dueckes** [comment]
Yep - honoring / calling the callback solved the problem (as per the README).
Will update - but happy for this one to be closed.

Many thanks for your quick response.
