### ISSUE TITLE
Upgrade from 1.0.0 to anything above causes 'RangeError: Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by honzajavorek** [cucumber/cucumber-js#602]
I tried to read the changelog, but I couldn't figure out what could cause this. There are no major changes, but still, 1.0.0 works perfectly fine for me, but 1.1.0 or 1.2.0 make them crash - see https://github.com/apiaryio/gavel.js/issues/60. Could anyone please give me some clues?

**Comment by jlin412** [comment]
Actually, I am getting RangeError even in 1.0.0 as well.

**Comment by charlierudolph** [comment]
In 0.9.3 the execution of each step was wrapped in `process.nextTick` in order to prevent stack overflows. Node 0.10 is quite old and will [stop being maintained in October](https://github.com/nodejs/LTS), when cucumber-js is also planning on dropping support for it.

A quick google search about that error makes it appear as if it only occurs in 0.10. Any chance you can upgrade to a newer node version?

**Comment by charlierudolph** [comment]
@honzajavorek any update on this? Otherwise going to close this out

**Comment by honzajavorek** [comment]
The thing is I still fully support 0.10 in [Dredd](http://github.com/apiaryio/dredd) and gavel.js. I'd have to drop support for 0.10 just because of a single dev dependency, which, to be honest, isn't a big motivation :-( Everything else works. So I guess I'm left with pinning cucumber.
