### ISSUE TITLE
If a scenario has no description, the json should put empty strings in scenario description

### ISSUE THREAD

**Issue by tfnico** [cucumber/cucumber-js#613]
Referring to [Cucumber's json output formatter](https://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter), a scenario element will always have a description attribute, with an empty string if there is no description:

```
{
        "keyword": "Scenario",
        "id": "one-passing-scenario,-one-failing-scenario;passing",
        "name": "Passing",
        "line": 5,
        "description": "",
....
```

Instead, cucumber-js seems to [omit the description](https://github.com/cucumber/cucumber-js/blob/master/features/json_formatter.feature) when it is missing in the feature. Some reporting tools like cukedoctor are [not able to handle JSON with this field missing](https://github.com/rmpestano/cukedoctor/issues/66). The correct thing to do, I'm guessing looking at the Cucumber spec linked above, is to always in include scenario description.

**Comment by charlierudolph** [comment]
That sounds good. Any chance you would like to try implementing this change?

After a quick look at the code it appears we are trying to include the description in the output but when the feature / scenario has no description its value is undefined instead of an empty string. `JSON.stringify` appears to omit properties that have a value of undefined. 

Note about those docs. They look extremely outdated. @aslakhellesoy @mattwynne can you confirm if these docs are outdated? Thoughts on bringing them up to date or even just removing them?

**Comment by tfnico** [comment]
@charlierudolph I don't think I can get around to doing much about this myself as I'm no JS-dev, and we're switching back to cucumber-jvm in my dayjob. Cukedoctor is now able to handle the missing fields, so for my sake this can be closed. Unless there's a Cucumber spec which is very clear about doing so, it feels a bit silly to cram empty fields into the JSON.
