### ISSUE TITLE
Impossible to setup timeout when using this.BeforeFeature

### ISSUE THREAD

**Issue by davidrissato** [cucumber/cucumber-js#625]
There is no way to setup a new timeout when using this.BeforeFeatures hook definition.

I tried the following without success:

```javascript
this.BeforeFeatures(
        function *(event) {
             // yield any operation longer than 5000 ms
        },
        { timeout: 20000 } // this timeout is completely ignored
);
```

and this:
```javascript
this.BeforeFeatures(
        { timeout: 20000 }, // this doesn't work either
        function *(event) {
             // yield any operation longer than 5000 ms
        }
);
```

However, the following syntax works fine and does what I wanted:

```javascript
this.registerHandler('BeforeFeatures',
       {timeout: 20000},
       function *(event) {
            // yield any operation longer than 5000 ms
       }
);
```

Is it a design choice?

**Comment by charlierudolph** [comment]
The syntax `this.BeforeFeatures` is undocumented and thus I didn't feel like adding the syntax to it. Since you can do the the same as `registerHandler`, I'd rather just deprecate it. I prefer `registerHandler` to separate it from `this.Before`. `this.Before` and `this.BeforeScenario` are very similar but one is dealing with the actual running of the scenario and one is just a hook.

**Comment by davidrissato** [comment]
I think @charlierudolph answered my question (about being a design choice), although I still think `this.BeforeFeatures` could be more readable and more convenient to use. Anyway, I'm closing this issue as there is no problem at all in using `this.registerHandler` to achieve the desired behaviour. Cheers.
