### ISSUE TITLE
Minor Issue: No Way to Continue After a Debugger

### ISSUE THREAD

**Issue by machineghost** [cucumber/cucumber-js#639]
When I use Cucumber.js I run it through Node so that I can enable debugging mode:

    nodejs --debug ./node_modules/.bin/cucumber.js test/cucumber

For the most part that works great: I can do:

    this.Then('I pause', () => {
        debugger;
    });

and add:

    I pause

anywhere in my tests to freeze the test execution and look at what's on the screen.

There's only one, relatively minor, problem: after the pause I have to `CTRL + C` out of the test, because there's no way to continue.  Normally when running Node in debug mode if you hit a debugger line you can proceed by hitting `c`, but for some reason that doesn't work with Cucumber.

It's not a big deal, because when you want to pause like that you're debugging, and so having to stop/re-run the test isn't a huge problem.  But if it's an easy fix, it would be nice if you could keep going through the test after a `debugger` (and if it's not then this should probably be closed as a "won't fix").

**Comment by charlierudolph** [comment]
Very interesting. I've never used debugger so I'm not certain about what the issue is here.

**Comment by machineghost** [comment]
>I've never used debugger

Hmmm, maybe I'm doing it wrong then?  When you get (say) an `ElementNotVisibleError: element not visible` when you're sure the element should be visible, how do you debug (or, to be more specific, how do you look at the page to see what's going on)?

> I'm not certain about what the issue is here.

There almost isn't one.  Everything works perfectly *except* that normally when you run Node in debug mode and it hits a `debugger` it pauses and presents you with a prompt where you can type `c` to continue (or other commands to inspect/debug).  However, it seems like Cucumber (or maybe Selenium) takes over in a way that prevents that prompt from appearing, so you're forced to `CTRL + C`.

**Comment by floribon** [comment]
@machineghost In case that can help, personally I'm using Protractor (wrapper of Selenium) and there's an interactive debugger that is started with `browser.pause()`. You can then either inspect your web page manually with a dev tool, or use a CLI to run selenium commands and see their results.

I assume there should be a similar functionality within the webdriver itself. Otherwise you can either inspect their code, or use it. It is intended for AngularJS apps but nothing forces you to use it in your project (as long as you set the `ignoreSynchronization` option).

But +1 out of curiosity to know how other people write and debug their tests.

**Comment by machineghost** [comment]
@floribon That's interesting, and it's almost enough to make me try Protractor ... but I'd still prefer not to add yet another tool to my environment (especially an Angular-centric one, since I have a React codebase), if I don't have to.

**Comment by charlierudolph** [comment]
Using the example in the docs, I was able to add `debugger;` in a step and was able to continue.  I was using node version 6.5.0 and used the command `node debug ./node_modules/.bin/cucumber.js`. 

Using `--debug` as a flag instead of a subcommand appears to be advanced usage in the [node docs](https://nodejs.org/api/debugger.html).

**Comment by machineghost** [comment]
@charlierudolph Removing the `--` before `debug` fixed it!  Sorry for what turned out not to actually be a  Cucumber-related ticket.
