### ISSUE TITLE
Resume from a specific point

### ISSUE THREAD

**Issue by remss** [cucumber/cucumber-js#653]
When a large test suite fails it is painful to restart all tests from the beginning.
Is there a way to resume from a specific point ?

Example if last run (with `--fail-fast`) did fail at `feature/foo.feature:55`
Let's resume with `cucumberjs feature --fail-fast --resume feature/foo.feature:55`

**Comment by charlierudolph** [comment]
There is no current solution, though I have definitely felt that pain many times before.

On possible solution is that we change fail fast to tell the formatters about each skipped scenario and change the rerun formatter also output skipped scenarios. Then after an early exit due to fail fast, you can use the rerun output to  run all remaining scenarios

**Comment by charlierudolph** [comment]
In `2.0.0-rc.1` you can use `--fail-fast` in conjunction with the rerun formatter in order to continue from the error.
