### ISSUE TITLE
Using a rerun file does not work when there is a trailing newline

### ISSUE THREAD

**Issue by haroldhues** [cucumber/cucumber-js#657]
I opened up a file created by the rerun formatted in vim and saving it (causing a new line character to be appended to the file). Once the newline is present, it seems to be _silently_ ignored by cucumberjs.

**Steps to reproduce: (v1.3.1)**
1. Run cucumber with a rerun formatted and at least one failing test
2. Open the rerun file (in vim)
3. Save the file
   - observe that there is now an extra new line character
4. Run cucumber with the rerun file

**Expected result:** Only the failing test is run again

**Actual result:** The rerun file seems to be skipped without an error or warning; all tests are run

**Comment by charlierudolph** [comment]
This was actually the cause of a bug when I initially implemented rerun. An extra newline in the file causes every feature to be loaded (this is because empty string gets treated as if its cwd and each directory get expanded to all recursive features).

Since this doesn't seem right, I think we should probably do two things. 
1) trim trailing whitespace from the rerun file to prevent your specific use case
2) throw an error if any feature path is an empty string (to prevent this odd case from causing any other bugs in the future)

If you'd like to just tackle number 1, I'm happy to point you in the right direction. 2 should be tackled separately whether you'd like to tackle it or not.

**Comment by charlierudolph** [comment]
[Here](https://github.com/cucumber/cucumber-js/blob/bbe5b86ddd5fc11fbc3009ec594124a8c29ca539/lib/cucumber/cli/configuration.js#L12) is where rerun files (files which start with a `@`) are read. 
Please add a failing feature test [here](https://github.com/cucumber/cucumber-js/blob/bbe5b86ddd5fc11fbc3009ec594124a8c29ca539/features/rerun_formatter.feature) first.
The test should could be very similar to the last four lines of `multiple scenarios failing` scenario. The first step would need to be changed to something like
```gherkin
Given a file named '@rerun.txt' with:
  # File content with an extra newline
```
