### ISSUE TITLE
Hooks don't catch Promise rejections

### ISSUE THREAD

**Issue by thomasvanlankveld** [cucumber/cucumber-js#676]
Given:

```gherkin
# features/something.feature
Feature: thing

Scenario: Something
  Given stuff
  When stuff
```

And:

```javascript
// features/step_definitions.js
module.exports = function() {
  this.BeforeFeatures(() => Promise.reject());
  this.defineStep(/^stuff$/, () => Promise.resolve());
};
```

The console outputs:

```
(node:3197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): node_modules/cucumber/lib/cucumber/support_code/library.js:17 Promise rejected
```

I get the same behavior for the other hooks. In my actual project, often the test runner also hangs on such rejections.

**Comment by thomasvanlankveld** [comment]
My current workaround:

```javascript
function printAsyncErrors(func) {
  return (scenario, callback) => {
    func(scenario).then(callback).catch(errr => {
      errr = errr || new Error('async operation failed');
      console.error(errr.stack);
      process.exit();
    });
  };
}

module.exports = function() {
  this.BeforeFeatures(printAsyncErrors(() => Promise.reject(new Error('boo!'))));
  this.defineStep(/^stuff$/, () => Promise.resolve());
};
```

**Comment by charlierudolph** [comment]
Just want to clarify some terminology. Hooks are only `this.Before` and `this.After` which are are involved in running tests. `BeforeFeatures` is an event handler for the cucumber lifecycle and any error in an event handler will end the suite. The interface you are using is syntactic sugar for 
```js
this.registerHandler('BeforeFeatures', /*...*/)
```
and will be removed in the next major release in order to separate the two a bit better.

When trying to reproduce I get the same error but the test suite exits. The reference `node_modules/cucumber/lib/cucumber/support_code/library.js:17` is definitely wrong but the rest of the stack appears correct to me. If you move to using `registerHandler` instead of the syntactic sugar that removes that reference. 

The event handler error is thrown after it is caught, which is what appears to add the "Unhandled Rejection" to the error message. We are throwing it instead of using console.error and manually exiting in order to let node/the browser determine how to print the error as just printing the stack doesn't work well in all browsers.

**Comment by thomasvanlankveld** [comment]
Thanks for clarifying!

To be clear, the I expect the suite to end when there is an error. The problem is I'm not seeing the stack. If you're letting node/the browser handle promise errors, I think this is intended behavior. The ECMAScript spec says unless there is an explicit `catch`, nothing should happen when a promise fails. I know the Node team is trying to figure out how to make this work for them. (in Node 7 you also get a `DeprecationWarning`, and I think in Node 8 they're just going to print the stack, although I think that would mean they're breaking the stack?)

I understand your reasons for leaving it up to node/the browser. However I now noticed some of my regular steps failing in this way, without a stack. Is this something I should be able to tackle with the function wrapper you mention in #514?

**Comment by charlierudolph** [comment]
> Is there any way to register an error to show up in the regular cucumber summary after all steps are complete? 

Nope. Errors from event handlers kill the suite because they should not be involved in running tests. Also `setDefinitionFunctionWrapper` only applies to hooks and step definitions.

**Comment by dueckes** [comment]
@charlierudolph 

Related question:
- Do handler promise rejections cause the cucumber command to exit with a non-zero status?

Related suggestion:
- Should these rejections be reported a warning?  Perhaps something more severe is appropriate given they kill the suite?

**Comment by charlierudolph** [comment]
@dueckes 

> Do handler promise rejections cause the cucumber command to exit with a non-zero status?

Yes. The suite should be killed immediately if there is a promise rejection.

> Should these rejections be reported a warning? Perhaps something more severe is appropriate given they kill the suite?

I don't understand what you mean. They aren't reported anywhere as the error kills the suite.

@thomasvanlankveld I believe this can be closed. Please reopen or create a new issue if there is something else to be discussed
