### ISSUE TITLE
Features order

### ISSUE THREAD

**Issue by lamartire** [cucumber/cucumber-js#760]
Hello, @jbpros!
I read [docs](https://github.com/cucumber/cucumber/wiki/Tags#running-a-subset-of-scenarios), but not found something about order run.
Can I specify the order of feature execution with global patterns?
```
cucumber --tags @first features/**/*
```
I mean run `@first` test and then run other tests.
Does it possible?

**Comment by aslakhellesoy** [comment]
Enforcing a particular order is something we discourage because it makes it impossible to run interdependent scenarios in isolation (which you need to do when you fix failing ones).

For this reason Cucumber will never help you run scenarios in a particular order.

Instead you should make sure they can run in any order.

**Comment by lamartire** [comment]
Got it. Thanks! :smile_cat:

**Comment by kidwm** [comment]
https://jkotests.wordpress.com/2013/08/22/specify-execution-order-of-cucumber-features/
How about support in this way like ruby version?

**Comment by NaveenKVN** [comment]
@aslakhellesoy  but its still ok to keep some possibility to execute in order rite, lets the users decide whether to use it or not. for eg, If i need to execute a step to generate some test data say a booking id before editing or cancelling the booking it will be useful. Appreciate if you could consider this.

**Comment by pantherqin** [comment]
Really appreciate if there is some options to set, to make sure all scenarios are running in their written order inside each individual feature file.
