### ISSUE TITLE
Add all available hooks to readme

### ISSUE THREAD

**Issue by jludvice** [cucumber/cucumber-js#783]
[Readme](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md) describes `Before` and `After` hooks, but it looks like there is more.

Eg. `beforeFeature` http://stackoverflow.com/questions/27605001/cucumber-js-get-current-feature-scenario-step-in-world
and some more mentioned in comments of #771.

Would it please be possible to add all available hooks into the `support_files/hooks.md` ?
Thank you :)

**Comment by KyleFairns** [comment]
In the wiki there is a page called [API Reference](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md) 

Under "registerHandler" on this page you'll see the [event list](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/event_handlers.md) that is linked, and that will tell you all of the available hooks.

**Comment by jludvice** [comment]
Ah, thank you for such quick response @KyleFairns, this helps a lot :)

**Comment by charlierudolph** [comment]
Sorry @jludvice. These event handlers are separated from the hooks because they serve different purposes. One key difference is the hooks also have the world instance while the event handlers do not. The API mentioned in that StackOverflow post was removed in 2.0 in order to remove the similar way you call them to help differtiate them.
