### ISSUE TITLE
Why cucumber steps are show as passed but the actual execution is not yet completed

### ISSUE THREAD

**Issue by nanichandu84** [cucumber/cucumber-js#802]
I am new to protractor cucumber framework. The problem I am facing is, when I ran my test, all the steps shows as executed even before the real execution is completed. How can I made cucumber step to wait till the execution is completed. Below is my code snippet.

this.Given(/^I go to sparqHomePage$/, function (callback) {
homepage.goToHomePage()
homepage.login(data[0].UserName,data[0].Password);
callback();
});

this.Then(/^I create a process$/, function (callback) {
homepage.clickDesign();
homepage.clickFlowDesigner();
console.log(params.flow.procName + ' '+ params.flow.procDesc);
designPage.createNewProc(params.flow.procName, params.flow.procDesc);
callback();
});

homepage is the page object for my homepage.

Any help is much appreciated.

**Comment by floribon** [comment]
You need to understand how the protractor (webdriver) control flow works: https://github.com/angular/protractor/blob/master/docs/control-flow.md

Cucumber is not aware of this flow and will consider the step done as soon as callback is called. Since you call `callback()` synchronously at the bottom of your step definitions it will be immediate.

What you need to do is wait for the last promise of this step to complete before letting cucumber know that it's ok to move on.

Option 1, wait for last promise and then call the callback: 
```js
this.Given(/^I go to sparqHomePage$/, function (callback) {
  homepage.goToHomePage();
  // assuming homepage.login returns a promise
  homepage.login(data[0].UserName,data[0].Password).then(function() {
    callback();
  }, function(err) {
    callback(err);
 })
});
```

Option 2 (recommended), omit the callback and simply return the last promise:
```js
this.Given(/^I go to sparqHomePage$/, function () {
  homepage.goToHomePage();
  // assuming homepage.login returns a promise
  return homepage.login(data[0].UserName,data[0].Password)
});
```

**Comment by nanichandu84** [comment]
Great, Spot on @floribon . That worked like a charm. Thank you so much for your help.
