### ISSUE TITLE
access the world object in defineSupportCode

### ISSUE THREAD

**Issue by dennyx** [cucumber/cucumber-js#808]
Hihi, would like to ask a question about how to access the world object in defineSupportCode method?
I wanna to set specified report name everytime run the test, and the report name specified from --world-parameters;
while I found the world object in defineSupportCode is undefined, which is an object in After method and could successfully get parameters, details as below:
![image](https://cloud.githubusercontent.com/assets/8176446/24577451/8470b2a8-1700-11e7-91b8-59aabf805668.png)
![image](https://cloud.githubusercontent.com/assets/8176446/24577455/957eb70c-1700-11e7-974e-7e2228aa4d17.png)

when I change the code to async way as below:
```javascript
 defineSupportCode( ({ registerHandler, registerListener, After, Before, setDefaultTimeout }) => {

    console.log("++++++++++++++++++ %s", JSON.stringify(this));
```
the world object show as {};

my dev dependencies as 
![image](https://cloud.githubusercontent.com/assets/8176446/24577536/10a2a0fa-1702-11e7-956d-ff0989f42809.png)

thanks~

**Comment by charlierudolph** [comment]
You cannot access the world object in `defineSupportCode`. A new world instance is created for each scenario and thus there is no world object when `defineSupportCode` runs. 

The difference in the `this` argument of `defineSupportCode` in the two cases you describe I believe is caused by using the arrow function which makes defineSupportCode have the context of its caller instead what cucumber calls the function with.

**Comment by dennyx** [comment]
Get it~thanks for the kindly response
