### ISSUE TITLE
the summarize failures is empty

### ISSUE THREAD

**Issue by manor21** [cucumber/cucumber-js#815]
cucumber js ver 1.2.0

when I run simple two steps , one pass(green) and the second fail(red), but the error is not printed in the Failures section in the end.

what can cause to this problem ?

thanks.

**Comment by charlierudolph** [comment]
Odd. Please provide a minimal reproducible example if you like to be further investigated.

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if needed

**Comment by twhitley** [comment]
May we reopen this issue?  I'm currently experiencing the same behavior.

**Comment by charlierudolph** [comment]
Can you please provide a minimal reproducible example?

**Comment by twhitley** [comment]
At the risk of appearing dense, I'll ask, what do you consider a minimum reproducible example?  This happens on all failures in my tests, no matter what.  The caveat is that we're using a custom framework, and I'm not sure what necessary components/information you'd need outlined in order to have appropriate context.

**Comment by aslakhellesoy** [comment]
How about:

* provide: a zip file or a git repo
* minimal: as few files as possible with as few lines as possible and as few module dependencies as possible
* reproducible: someone can run `npm install && npm test` to see what you're seeing

**Comment by twhitley** [comment]
Just to close the support loop I re-opened, I was running with cucumber v1.3.0 and updating to v.1.3.3 fixed it.
