### ISSUE TITLE
@allow-rescue or equivalent to overwrite feature/scenario result

### ISSUE THREAD

**Issue by picklelv** [cucumber/cucumber-js#856]
Is the `@allow-rescue` tag available in cucumber-js?  I'm looking for the ability to implement a tag `@known-failure` that we can use when a bug exists in our application.  The feature/scenario result would be `pass` with that tag until the feature/scenario passes, then result would be `fail` until we removed the tag.

**Comment by charlierudolph** [comment]
Neither of those tags are treated in a special way by cucumber-js. Personally I don't think either should be built. I don't think the scenario should be run if you expect it to fail. You could write the scenario in another way so that it verifies the bug exists. That would fail when the bug is fixed and could then be updated to verify that it works as expected

**Comment by charlierudolph** [comment]
@mattwynne @aslakhellesoy any thoughts on this? I personally don't think any tags should be treated special by the framework.

**Comment by charlierudolph** [comment]
Closing due to age and lack of response

**Comment by mattwynne** [comment]
It seems to me this kind of functionality would be well suited to a little plugin.
