### ISSUE TITLE
Ambiguous match due to global uniqueness ignoring Given/When/Then

### ISSUE THREAD

**Issue by nomad3k** [cucumber/cucumber-js#880]
Cucumber-js currently complains about ambiguous matches for patterns that cannot apply.

Patterns should only be unique within the Given, When, Then.

e.g. 

    Given bacon is life
     When I eat bacon
     Then bacon is gone

And the following steps:

    defineSupportCode(function({Given, When, Then}) {
      Given('bacon is {\S+}', function(statement) { });
      When('I {\S+} bacon', function(verb) { });
      Then('bacon is {\S+}', function(state) { });
    });

Generates the following error:

    Multiple step definitions match:
      bacon is {S+} - feature\support\step.js:8
      bacon is {S+} - feature\support\step.js:14

It shouldn't matter that I use the same statement in a Given and Then block, because there's no way they can be used like that.

**Comment by nomad3k** [comment]
p.s. Can you tell I've not had breakfast yet?

**Comment by charlierudolph** [comment]
> Patterns should only be unique within the Given, When, Then.

I also thought this when I started working with cucumber. However, it has been a long standing idea that the code treats Given/When/Then all the same. Patterns need to be unique globally as the error suggests. I'd suggest making the pattern for the `Then` step be something like `'bacon should be {S+}'`.

@aslakhellesoy any more context you can give to the matter. I'd like to give an answer to this on our FAQ. I would say the reason is to avoid using the same language so that the same statement doesn't mean different things. Do you have a more detailed explanation?

**Comment by aslakhellesoy** [comment]
Sort of unrelated, but your expressions are weird. When you use strings (and not regexp) your string is interpreted as a Cucumber Expression. However, your strings don't look like Cucumber Expressions. `{S+}` refers to a parameter type named `S+` which is really odd.

**Comment by aslakhellesoy** [comment]
The reason why they are global is to encourage a ubiquitous, non-ambiguous domain language. There are numerous threads about this in the mailing list archives.

**Comment by charlierudolph** [comment]
Added this to the FAQ.
