### ISSUE TITLE
Cannot read property 'on' of undefined at new JsonFormatter

### ISSUE THREAD

**Issue by VaaniSai** [cucumber/cucumber-js#910]
I am trying to generate a html report using **cucumber-html-reporter**. But I believe its the issue with cucumber.

getting error:
`Unhandled rejection TypeError: Cannot read property 'on' of undefined
    at new JsonFormatter (C:\path-to-project\node_modules\cucumber\src\formatter\json_formatter.js:21:5)
    at Object.<anonymous> (C:\path-to-project\test\reporting\CucumberReportExtension.ts:43:27)`

Checked [release notes](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md) for undefined parameters. I am not sure whether this issue belong to that!
If so, can anyone please drive me to fix this issue.

Also please let me know in case you have better solution to generate reports with cucumber-protractor using typescript. (Please consider the below versions too)

Below are my project details:

Protractor version: **5.1.2**
Cucumber version: **3.0.0**

**ScenarioHook.ts**

    import {defineSupportCode} from "cucumber";
    import {CucumberReportExtension} from "../reporting/CucumberReportExtension";
    defineSupportCode(({AfterAll}) => {

     AfterAll(async () => {
        new CucumberReportExtension().myJsonFormatter;
       });
    });

**CucumberReportExtension.ts**

     import * as fs from 'fs';
     import { mkdirp } from 'mkdirp';
     import * as report from 'cucumber-html-reporter';
     let Cucumber = require('cucumber');

     export class CucumberReportExtension {

       private jsonDir = process.cwd() + "/reports/json";
       private htmlDir = process.cwd() + "/reports/html";
       private jsonFile = this.jsonDir + "/cucumber_report.json";
 
     private cucumberReporterOptions = {
        theme: "bootstrap",
        jsonFile: this.jsonFile,
        output: this.htmlDir + "/cucumber_reporter.html",
        reportSuiteAsScenarios: true,
        metadata: {
            "App Version":"0.0.1",
            "Test Environment": "TestingMicroSheet",
            "Browser": "Chrome  59.0.945",
            "Platform": "Windows 10",
            "Parallel": "Scenarios",
            "Executed": "Local"
           }
     };

     private CreateReportFile(dirName, fileName, fileContent) {
        //Check if the directory exist
        if (!fs.existsSync(dirName))
            mkdirp.sync(dirName);
        try {
            fs.writeFileSync(fileName, fileContent);
           }
        catch (message) {
            console.log("Failed to create File/Directory :" + message);
             }
       }

     private GenerateCucumberReport(cucumberReportOption){
        report.generate(cucumberReportOption);
        }

     myJsonFormatter = new Cucumber.JsonFormatter({
        log: jLog => {
            this.CreateReportFile(this.jsonDir, this.jsonFile, jLog);
            this.GenerateCucumberReport(this.cucumberReporterOptions);
            }
       });
    }
     export let JsonFormatter = new CucumberReportExtension().myJsonFormatter ;

**config.ts**

     import { Config } from 'protractor';

     export let config: Config = {
         seleniumAddress: 'http://localhost:4444/wd/hub',
          framework: 'custom',
          frameworkPath: require.resolve('protractor-cucumber-framework'),
          specs: ["../features/*.feature"],

          baseUrl: "http://localhost:4200/",

          cucumberOpts: {
              compiler: "ts:ts-node/register",
              strict: true,
              format: ['json:../reporting/results.json'],
              require: ['../steps/*.js', '../hooks/*.js'],
              tags: '@smoke'
           }
       }

**package.json**

     {
         "name": "protractor-cucumber-sample",
        "version": "0.0.0",
        "private": true,
        "scripts": {
        "start": "node ./bin/www"
           },
        "dependencies": {
          "@types/jasmine": "^2.5.53",
          "body-parser": "~1.17.1",
          "cookie-parser": "~1.4.3",
          "debug": "~2.6.3",
          "express": "~4.15.2",
          "jade": "~1.11.0",
          "morgan": "~1.8.1",
          "serve-favicon": "~2.4.2"
            },
        "devDependencies": {
         "@types/chai": "^4.0.3",
         "@types/cucumber": "^2.0.3",
         "@types/mkdirp": "^0.5.0",
         "chai": "^4.1.1",
         "chai-as-promised": "^7.1.1",
         "cucumber": "^3.0.0",
         "cucumber-html-reporter": "^2.0.3",
         "jasmine": "^2.7.0",
         "jasminewd2": "^2.1.0",
         "protractor-cucumber-framework": "^4.0.2",
         "ts-node": "^3.3.0",
         "typescript": "^2.4.2"
           }
    }

Please let me know if additional information required which helps you to address this issue.

If this is not the right forum, could you please reply me with the right forum details to post this issue.

Thanks in advance.

**Comment by charlierudolph** [comment]
It appears cucumber-html-reporter added support for cucumber 3 with version 3.0.0. 

Also your `CucumberReportExtension` now appears outdated. The JsonFormatter needs to be passed in an EventBroadcaster. I would suggest against using the JsonFormatter directly in that way. Instead I'd suggest parsing the json formatter result in a separate node process after cucumber-js finishes running

**Comment by wswebcreation** [comment]
@charlierudolph 

I just have a question that I think is related to this issue. 

In our current usage (cucumber, v1 and later v2, protractor and protractor-cucumber-framework) we used the `registerListener()` in combination with the `jsonFormatter` to extend the json-file before the file was written to disk. The data that is extended is the data of the current capability, like browsername, OS name and so on.

The setup could be run for 1 capability or for multi capabilities. When 1 capability is used the new setup in Cucumber 3 can be used to use a different node process to adjust the save json file. When we have multi capabilities we are not able to extend the file with the capability data because we don't know the connection between the instance and the json file.

I've been reading a lot in the documentation and in the PR / issue list, but I can't find a way to "adjust" the json before or after running the feature files.

Do you have an solution /  example for this?

**Comment by charlierudolph** [comment]
> The setup could be run for 1 capability or for multi capabilities. When 1 capability is used the new setup in Cucumber 3 can be used to use a different node process to adjust the save json file. When we have multi capabilities we are not able to extend the file with the capability data because we don't know the connection between the instance and the json file.

Why do you not know the connection between the instance and the json file? Is there one json file per capability?

> I've been reading a lot in the documentation and in the PR / issue list, but I can't find a way to "adjust" the json before or after running the feature files.

I don't believe this is possible and I'm surprised this was ever possible. A custom formatter extends the json formatter might be one possible solution as you could override the function that logs the output with a function that adjusts the json and then writes it

**Comment by wswebcreation** [comment]
> Why do you not know the connection between the instance and the json file? Is there one json file per capability?

Yes, with Protractor you can have a 1 on 1 connection between the instance and the json file.

> I don't believe this is possible and I'm surprised this was ever possible. 

It was a few lines of code, but this has been there since Cucumber version 1, see the below code example where I'm also saving a separate json file per feature if there are more features in a json file

``ts
import { Capabilities } from 'selenium-webdriver';
import { browser } from 'protractor';
import { defineSupportCode } from 'cucumber';
import { ensureDirSync, readdirSync, removeSync } from 'fs-extra';
import { join } from 'path';

const Cucumber = require('cucumber');// tslint:disable-line
const jsonFormatter = new Cucumber.JsonFormatter();
const jsonFile = require('jsonfile');// tslint:disable-line
const projectRoot = process.cwd();

defineSupportCode(({ registerListener }) => {
    registerListener(jsonFormatter);

    return _generateAndSaveJsonFile();

    /**
     * Generate and save the report json files
     */
    async function _generateAndSaveJsonFile(): Promise<void> {
        jsonFormatter.log = async function (report: string) {
            const capabilities = await browser.getCapabilities();
            await _adjustAndSaveJsonFile(capabilities, report);
        };
    }

    /**
     * Adjust and save the json files
     */
    function _adjustAndSaveJsonFile(capabilities: Capabilities, report: string) {
        const browserName = capabilities.get('browserName');
        const jsonReport = JSON.parse(report);
        const deviceType = browser.deviceProperties.deviceType.toLowerCase();

        if (jsonReport[0] !== null) {
            const metadata = {
                'browser': {
                    'name': browser.deviceProperties.browser.name,
                    'version': browser.deviceProperties.browser.version
                },
                'device': browser.deviceProperties.device,
                'platform': {
                    'name': browser.deviceProperties.platform.name,
                    'version': browser.deviceProperties.platform.version
                }
            };
            const jsonOutputFolder = join(projectRoot, '.tmp/json-output');

            ensureDirSync(jsonOutputFolder);

            jsonReport.forEach((singleReport: any) => {
                const featureName = singleReport.name.replace(/\s+/g, '_').replace(/\W/g, '').toLowerCase() || 'noName';
                const filePath = join(jsonOutputFolder, `${featureName}.${browserName}.${deviceType}_${Date.now()}.json`);

                // Remove a previous file if it exists to prevent double reports of 1 feature + browser execution
                readdirSync(jsonOutputFolder)
                    .filter((file) => file.match(new RegExp(`${featureName}.${browserName}.${deviceType}`, 'ig')))
                    .forEach((file) => removeSync(join(projectRoot, `.tmp/json-output/${file}`)));

                singleReport.metadata = metadata;
                jsonFile.writeFileSync(filePath, JSON.parse(`[${JSON.stringify(singleReport)}]`), { spaces: 2 });
            });
        }
    }
});
```

> A custom formatter extends the json formatter might be one possible solution as you could override the function that logs the output with a function that adjusts the json and then writes it

I'm curious how to do that, because I need to adjust the json in the beforeAll / afterAll and that isn't possible anymore (or I'm missing something) because I can't find any docs on how to adjust the log on the root level of the feature. If you can help me with that / point me in the right direction I can also add that as a PR to the docs if you want.

Tnx in advance

**Comment by wswebcreation** [comment]
@charlierudolph ,

Do you have a solution for the above? Because I'm banging my head against the wall now because I don't know where to search for a proper solution for this. This prevents me from upgrading to version 3 :(

**Comment by VaaniSai** [comment]
I switched back to cucumber V2.3.0 as I could not fix JsonFormatter error in cucumber V3.0.0.

**Comment by charlierudolph** [comment]
There is not way to do this in the v3 at the moment. Since you are starting cucumber-js x number of times, can you update the json file output name in order to be able to tell the difference between each capability and thus be able to parse the json formatter result in a separate node process after cucumber-js finishes running?

**Comment by wswebcreation** [comment]
Hi @charlierudolph 

I can do that with protractor-cucumber-framework, but then there is a situation in which the file is still overwritten (see issue [here](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/99))

I'm now trying to find where the code is that writes the json to a file, is that in cucumber? Because I can't find it.

**Comment by darrinholst** [comment]
[here?](https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter.js#L100)

**Comment by wswebcreation** [comment]
@daririnholst

I found it [here](https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L38) and created an issue / question for it [here](https://github.com/cucumber/cucumber-js/issues/926)

**Comment by josepmc** [comment]
We're also using this functionality in Cucumber 2.3.0. In our case we're using it in order to have multiple outputs. We're using a 'Pretty' formatter to show the results as they go, a 'rerun' to show the final results and a 'json' in order to create html and pdf versions of the tests.
Additionally we aggregate all the json results into a final combined PDF and HTML result.

Is support for this planned for Cucumber 3.x?

**Comment by charlierudolph** [comment]
@josepmc The CLI support multiple formats and outputs, could that be used? 

Closing this as the original issue has been addressed. 
Please create new issues is need be
