### ISSUE TITLE
What is replacement of registerHandler('AfterFeatures') in v3?

### ISSUE THREAD

**Issue by ramneetatnewwave** [cucumber/cucumber-js#918]
With v2, I used following to modify my json report at the end of the test to ensure my reporting tool can show what I need:

`registerHandler('AfterFeatures', function(event, callback) {}`

After upgrading to v3, I dont have registerHandler available, and `AfterAll` hook is run after all scenarios have finished, instead of after all features.

What should I use if I need to execute a code after all features have finished and report is ready?

**Comment by charlierudolph** [comment]
Use a separate node executable that you run after the cucumber-js process finishes

**Comment by tony-kerz** [comment]
would this apply to `BeforeFeatures` as well?

**Comment by charlierudolph** [comment]
Does 'BeforeAl'l not work for your use case?

**Comment by tony-kerz** [comment]
my understanding is that `BeforeAll` runs before-all-scenarios for a feature?
(so it's kind of like `BeforeFeature`?).

i think it would work for me, but in some of the use-cases i have encountered,
i do initialization that spans multiple features, like:

1. initialize an entire database, or
1. start an express server to respond to restful requests

it would be less performant to do those steps multiple times between features than once before-all-features.

i think it might be easier to reason about holistically if there were hooks in the cucumber lifecycle to accommodate those types of events instead of having to involve another mechanism such as npm pre/post steps...?

**Comment by yaronassa** [comment]
`BeforeAll` runs before all scenarios, period.
Which means that the cucumber infrastructure has been built and initialized, but no scenario has been run.

It sounds like it could be relevant to the cases you've described.
However, if you have feature-dependent initialization (i.e., something to run before/after a given **feature**), AFAIK there's no V3 hook for it.

**Comment by tony-kerz** [comment]
thanks yaron, then since `BeforeAll` works similarly to `BeforeFeatures`, i should be all set 👍 

appreciate you setting me straight on that!
