### ISSUE TITLE
Case insensitive regex in Step Definition doesn't match

### ISSUE THREAD

**Issue by dmeehan1968** [cucumber/cucumber-js#970]
I'm trying to implement a case insensitive step definition ('i' flag) but it fails to match when the Step contains uppercase, where the regex is defined in lowercase.

Basically, it only works if the Step contains the same case as the regex.  The 'i' flag appears to have no effect, as if its being stripped off.

I'm trying to run this in a Node v8.4.0 environment.

The following snippets illustrate:

```
// steps.js snippet
Given(/^case insensitive$/i, function() {

});
```

```
# test.feature snippet
Feature: Case insensitive regular expressions

  Scenario: This should match, but doesn't
    Given Case Insensitive

  Scenario: This should match, and does
    Given case insensitive

```

Here is the output from cucumber:
```
Warnings:

1) Scenario: This should match, but doesn't # features/test/case-insensitive.js:6
   ? Given CASE INSENSITIVE
       Undefined. Implement with the following snippet:

         Given('CASE INSENSITIVE', function (callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });
       

2) Scenario: This should match, but doesn't # features/rest-api/delete-todo-by-id.feature:9
   ? Given Case Insensitive
       Undefined. Implement with the following snippet:

         Given('Case Insensitive', function (callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });
       
```

**Comment by charlierudolph** [comment]
@aslakhellesoy looked into this and I believe the problem is with the library `becke-ch--regex--s0-0-v1--base--pl--lib` which is used in `cucumber-expressions`. When passed in a regular expression, it the flags are stripped.

That library doesn't have a way to report bugs that i can find but it appears the api accepts flags as the second parameter (when inspecting the source).

**Comment by aslakhellesoy** [comment]
I'll have a look

**Comment by aslakhellesoy** [comment]
The reason I added that library is to be able to find the start and end of groups, which isn't supported by JavaScript's regexp. The problem is described [here](https://stackoverflow.com/questions/1985594/how-to-find-indices-of-groups-in-javascript-regular-expressions-match).

While the [becke](http://www--s0-v1.becke.ch/tool/becke-ch--regex--s0-v1/becke-ch--regex--s0-0-v1--homepage--pl--client/) lib supports this, it's undeniably a liability to depend on it, so I think we need to build our own logic for this.

**Comment by dmeehan1968** [comment]
A possible workaround, if the dependency cannot be easily fixed/replaced, would be to modify line 7 of tree_regexp.js, where the Regex is created, to pass the regexp source and flags instead of the original regexp.

this._regex = new Regex(this._re.source, this._re.flags);

The bug in the underlying library appears to only occur if a RegExp instance is passed.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber#300
