### ISSUE TITLE
Before hook should include feature metadata

### ISSUE THREAD

**Issue by csvan** [cucumber/cucumber-js#979]
Currently, the options passed to the Before hook only include information about the Scenario- not the Feature which it falls under. 

An exception to this are the tags associated with the Feature - these are added to the `pickle.tags` part of the options. None of the other Feature data - such as the name - are present however. For consistency and flexibility they should be.

**Comment by charlierudolph** [comment]
What would such data be used for? 

Pickles are objects that come from parsing the feature files. Each scenario becomes a pickle and each example row of a scenario outline becomes a pickle. These elements are meant to contain only the information necessary for running tests. The tags are present because of the rules of how tags are inherited and because tags for filtering what pickles to run.

**Comment by charlierudolph** [comment]
Closing due to age and lack of response. Please reopen if needed
