### ISSUE TITLE
Step with a negative value. 

### ISSUE THREAD

**Issue by piotro83** [cucumber/cucumber-js#983]
```
When i set negative value -2

this.When(/^i set negatice value \-2$/, function (callback) {
        callback.pending();
    });
```

I am green, so please help me how to set it?
step is not recognized

```
When i set negative value 2
this.When(/^i set value (\d+)$/, function (arg1, callback) {
        callback.pending();
    });
```

**Comment by charlierudolph** [comment]
I'm a bit confused by this. Are you saying case 1 works and case 2 does not?

---
### Case 1
step: `When i set negative value -2`
step definition:
```js
this.When(/^i set negatice value \-2$/, function (callback) {
  callback.pending();
});
```
---
### Case 2
step: `When i set negative value 2`
step definition:
```js
this.When(/^i set value (\d+)$/, function (arg1, callback) {
  callback.pending();
});
```
---
I don't expect either to work. For case 1, the step has word "negative" while the step definition has "negatice" (v -> c). For case 2, the second has the word "negative" while the step definition does not.

If you asking about how to use a regular expression in order to catch positive and negative number that could be dealt, that can be done with `(-?\d+)`. I would also suggest checking out [cucumber-expressions](https://docs.cucumber.io/cucumber-expressions/) as this allows you to avoid having to write regular expressions for a lot of the common things captured.

**Comment by piotro83** [comment]
@charlierudolph thanks for info but I still have a problem. Maybe you help me?

Why i have Undefined step references in first step?
https://wpde.sk/pp/1rnzk.png

` "devDependencies": {`
    `"cucumber": "~3.2.0",`
    `"protractor": "~5.2.1",`
    `"protractor-cucumber-framework": "~4.1.1",`
    `"selenium-webdriver": "~3.6.0",`
    `"cucumber-expressions": "5.0.7"`
	},`

when i run test i have 2 Undefined steps:
> Warnings:

1) Scenario: test # test-acceptance\features\test.feature:3
   ? When I have 3 cucumbers in my belly
       Undefined. Implement with the following snippet:

         When('I have {int} cucumbers in my belly', function (int, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });

   ? When I give you 3 toys
       Undefined. Implement with the following snippet:

         When('I give you {int} toys', function (int, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });


1 scenario (1 undefined)
2 steps (2 undefined)

**Comment by charlierudolph** [comment]
I don't know what your step definitions are and unless you have one that would match, a step is undefined. You appear to be using protractor which builds on top of cucumber. Please ask you question at `protractor-cucumber-framework` and only bring issues here if they could not be resolved there. 

Also issues are meant to be used for bug reports / feature requests. If you need help using cucumber their are support forums: https://cucumber.io/support. `protractor-cucumber-framework` may have something similar
