### ISSUE TITLE
add debugging

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#996]
By adding `--debug` cucumber will output additional data while its running helping people debug why things aren't working.

* output what interface each step uses (synchronous, promise, or callback) see #974

Open to other ideas as well

**Comment by lenntt** [comment]
Think `why things aren't working` is a bit hard to generalize and instead of adding `--debug` (or `--verbose`), 
I think the first goal should be to improve the feedback/messages when things go wrong.

In the linked issue, I don't think this kind of feedback helped (commented in the original issue).

the best debug info, you get from a debugger :)
```
node --inspect --debug-brk node_modules/cucumber/bin/cucumber-js
```

**Comment by lenntt** [comment]
in order words: I suggest closing this, at least until we've a good/concrete use case.

**Comment by charlierudolph** [comment]
True. This can only deal with a missing return on the top level and not in a nested promise. Closing.
